/*
Berth API

Testing OperationLogsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package berth

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tech-arch1tect/berth-go-api-client"
)

func Test_berth_OperationLogsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test OperationLogsAPIService ApiV1AdminOperationLogsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OperationLogsAPI.ApiV1AdminOperationLogsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperationLogsAPIService ApiV1AdminOperationLogsIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.OperationLogsAPI.ApiV1AdminOperationLogsIdGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperationLogsAPIService ApiV1AdminOperationLogsStatsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OperationLogsAPI.ApiV1AdminOperationLogsStatsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperationLogsAPIService ApiV1OperationLogsByOperationIdOperationIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var operationId string

		resp, httpRes, err := apiClient.OperationLogsAPI.ApiV1OperationLogsByOperationIdOperationIdGet(context.Background(), operationId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperationLogsAPIService ApiV1OperationLogsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OperationLogsAPI.ApiV1OperationLogsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperationLogsAPIService ApiV1OperationLogsIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.OperationLogsAPI.ApiV1OperationLogsIdGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperationLogsAPIService ApiV1OperationLogsStatsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OperationLogsAPI.ApiV1OperationLogsStatsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test OperationLogsAPIService ApiV1RunningOperationsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.OperationLogsAPI.ApiV1RunningOperationsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
