/*
Berth API

Testing FilesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package berth

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tech-arch1tect/berth-go-api-client"
)

func Test_berth_FilesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesChmodPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesChmodPost(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesChownPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesChownPost(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesCopyPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesCopyPost(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesDeleteDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesDeleteDelete(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesDownloadGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesDownloadGet(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesGet(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesMkdirPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesMkdirPost(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesReadGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesReadGet(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesRenamePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesRenamePost(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesStatsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesStatsGet(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesUploadPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesUploadPost(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test FilesAPIService ApiV1ServersServeridStacksStacknameFilesWritePost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var serverid int32
		var stackname string

		resp, httpRes, err := apiClient.FilesAPI.ApiV1ServersServeridStacksStacknameFilesWritePost(context.Background(), serverid, stackname).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
