/*
Berth API

Testing SecurityAuditAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package berth

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/tech-arch1tect/berth-go-api-client"
)

func Test_berth_SecurityAuditAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SecurityAuditAPIService ApiV1AdminSecurityAuditLogsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SecurityAuditAPI.ApiV1AdminSecurityAuditLogsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecurityAuditAPIService ApiV1AdminSecurityAuditLogsIdGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id int32

		resp, httpRes, err := apiClient.SecurityAuditAPI.ApiV1AdminSecurityAuditLogsIdGet(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecurityAuditAPIService ApiV1AdminSecurityAuditLogsStatsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.SecurityAuditAPI.ApiV1AdminSecurityAuditLogsStatsGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
