/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetScanTrendData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetScanTrendData{}

// GetScanTrendData struct for GetScanTrendData
type GetScanTrendData struct {
	PerImageTrend []PerImageTrend `json:"per_image_trend"`
	ScopeWarning *string `json:"scope_warning,omitempty"`
	StackTrend []ScanTrendPoint `json:"stack_trend"`
}

type _GetScanTrendData GetScanTrendData

// NewGetScanTrendData instantiates a new GetScanTrendData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetScanTrendData(perImageTrend []PerImageTrend, stackTrend []ScanTrendPoint) *GetScanTrendData {
	this := GetScanTrendData{}
	this.PerImageTrend = perImageTrend
	this.StackTrend = stackTrend
	return &this
}

// NewGetScanTrendDataWithDefaults instantiates a new GetScanTrendData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetScanTrendDataWithDefaults() *GetScanTrendData {
	this := GetScanTrendData{}
	return &this
}

// GetPerImageTrend returns the PerImageTrend field value
func (o *GetScanTrendData) GetPerImageTrend() []PerImageTrend {
	if o == nil {
		var ret []PerImageTrend
		return ret
	}

	return o.PerImageTrend
}

// GetPerImageTrendOk returns a tuple with the PerImageTrend field value
// and a boolean to check if the value has been set.
func (o *GetScanTrendData) GetPerImageTrendOk() ([]PerImageTrend, bool) {
	if o == nil {
		return nil, false
	}
	return o.PerImageTrend, true
}

// SetPerImageTrend sets field value
func (o *GetScanTrendData) SetPerImageTrend(v []PerImageTrend) {
	o.PerImageTrend = v
}

// GetScopeWarning returns the ScopeWarning field value if set, zero value otherwise.
func (o *GetScanTrendData) GetScopeWarning() string {
	if o == nil || IsNil(o.ScopeWarning) {
		var ret string
		return ret
	}
	return *o.ScopeWarning
}

// GetScopeWarningOk returns a tuple with the ScopeWarning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetScanTrendData) GetScopeWarningOk() (*string, bool) {
	if o == nil || IsNil(o.ScopeWarning) {
		return nil, false
	}
	return o.ScopeWarning, true
}

// HasScopeWarning returns a boolean if a field has been set.
func (o *GetScanTrendData) HasScopeWarning() bool {
	if o != nil && !IsNil(o.ScopeWarning) {
		return true
	}

	return false
}

// SetScopeWarning gets a reference to the given string and assigns it to the ScopeWarning field.
func (o *GetScanTrendData) SetScopeWarning(v string) {
	o.ScopeWarning = &v
}

// GetStackTrend returns the StackTrend field value
func (o *GetScanTrendData) GetStackTrend() []ScanTrendPoint {
	if o == nil {
		var ret []ScanTrendPoint
		return ret
	}

	return o.StackTrend
}

// GetStackTrendOk returns a tuple with the StackTrend field value
// and a boolean to check if the value has been set.
func (o *GetScanTrendData) GetStackTrendOk() ([]ScanTrendPoint, bool) {
	if o == nil {
		return nil, false
	}
	return o.StackTrend, true
}

// SetStackTrend sets field value
func (o *GetScanTrendData) SetStackTrend(v []ScanTrendPoint) {
	o.StackTrend = v
}

func (o GetScanTrendData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetScanTrendData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["per_image_trend"] = o.PerImageTrend
	if !IsNil(o.ScopeWarning) {
		toSerialize["scope_warning"] = o.ScopeWarning
	}
	toSerialize["stack_trend"] = o.StackTrend
	return toSerialize, nil
}

func (o *GetScanTrendData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"per_image_trend",
		"stack_trend",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetScanTrendData := _GetScanTrendData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetScanTrendData)

	if err != nil {
		return err
	}

	*o = GetScanTrendData(varGetScanTrendData)

	return err
}

type NullableGetScanTrendData struct {
	value *GetScanTrendData
	isSet bool
}

func (v NullableGetScanTrendData) Get() *GetScanTrendData {
	return v.value
}

func (v *NullableGetScanTrendData) Set(val *GetScanTrendData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetScanTrendData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetScanTrendData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetScanTrendData(val *GetScanTrendData) *NullableGetScanTrendData {
	return &NullableGetScanTrendData{value: val, isSet: true}
}

func (v NullableGetScanTrendData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetScanTrendData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


