/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResponseOperationLogInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponseOperationLogInfo{}

// ResponseOperationLogInfo struct for ResponseOperationLogInfo
type ResponseOperationLogInfo struct {
	Data []OperationLogInfo `json:"data"`
	Error NullableError `json:"error,omitempty"`
	Meta NullableMeta `json:"meta,omitempty"`
	Success bool `json:"success"`
}

type _ResponseOperationLogInfo ResponseOperationLogInfo

// NewResponseOperationLogInfo instantiates a new ResponseOperationLogInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponseOperationLogInfo(data []OperationLogInfo, success bool) *ResponseOperationLogInfo {
	this := ResponseOperationLogInfo{}
	this.Data = data
	this.Success = success
	return &this
}

// NewResponseOperationLogInfoWithDefaults instantiates a new ResponseOperationLogInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponseOperationLogInfoWithDefaults() *ResponseOperationLogInfo {
	this := ResponseOperationLogInfo{}
	return &this
}

// GetData returns the Data field value
func (o *ResponseOperationLogInfo) GetData() []OperationLogInfo {
	if o == nil {
		var ret []OperationLogInfo
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ResponseOperationLogInfo) GetDataOk() ([]OperationLogInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ResponseOperationLogInfo) SetData(v []OperationLogInfo) {
	o.Data = v
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseOperationLogInfo) GetError() Error {
	if o == nil || IsNil(o.Error.Get()) {
		var ret Error
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseOperationLogInfo) GetErrorOk() (*Error, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *ResponseOperationLogInfo) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableError and assigns it to the Error field.
func (o *ResponseOperationLogInfo) SetError(v Error) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *ResponseOperationLogInfo) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *ResponseOperationLogInfo) UnsetError() {
	o.Error.Unset()
}

// GetMeta returns the Meta field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ResponseOperationLogInfo) GetMeta() Meta {
	if o == nil || IsNil(o.Meta.Get()) {
		var ret Meta
		return ret
	}
	return *o.Meta.Get()
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ResponseOperationLogInfo) GetMetaOk() (*Meta, bool) {
	if o == nil {
		return nil, false
	}
	return o.Meta.Get(), o.Meta.IsSet()
}

// HasMeta returns a boolean if a field has been set.
func (o *ResponseOperationLogInfo) HasMeta() bool {
	if o != nil && o.Meta.IsSet() {
		return true
	}

	return false
}

// SetMeta gets a reference to the given NullableMeta and assigns it to the Meta field.
func (o *ResponseOperationLogInfo) SetMeta(v Meta) {
	o.Meta.Set(&v)
}
// SetMetaNil sets the value for Meta to be an explicit nil
func (o *ResponseOperationLogInfo) SetMetaNil() {
	o.Meta.Set(nil)
}

// UnsetMeta ensures that no value is present for Meta, not even an explicit nil
func (o *ResponseOperationLogInfo) UnsetMeta() {
	o.Meta.Unset()
}

// GetSuccess returns the Success field value
func (o *ResponseOperationLogInfo) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ResponseOperationLogInfo) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ResponseOperationLogInfo) SetSuccess(v bool) {
	o.Success = v
}

func (o ResponseOperationLogInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponseOperationLogInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	if o.Meta.IsSet() {
		toSerialize["meta"] = o.Meta.Get()
	}
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *ResponseOperationLogInfo) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResponseOperationLogInfo := _ResponseOperationLogInfo{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResponseOperationLogInfo)

	if err != nil {
		return err
	}

	*o = ResponseOperationLogInfo(varResponseOperationLogInfo)

	return err
}

type NullableResponseOperationLogInfo struct {
	value *ResponseOperationLogInfo
	isSet bool
}

func (v NullableResponseOperationLogInfo) Get() *ResponseOperationLogInfo {
	return v.value
}

func (v *NullableResponseOperationLogInfo) Set(val *ResponseOperationLogInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableResponseOperationLogInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableResponseOperationLogInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponseOperationLogInfo(val *ResponseOperationLogInfo) *NullableResponseOperationLogInfo {
	return &NullableResponseOperationLogInfo{value: val, isSet: true}
}

func (v NullableResponseOperationLogInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponseOperationLogInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


