/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StackDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackDetails{}

// StackDetails struct for StackDetails
type StackDetails struct {
	ComposeFile string `json:"compose_file"`
	Name string `json:"name"`
	Path string `json:"path"`
	ServerId int32 `json:"server_id"`
	ServerName string `json:"server_name"`
	Services []ComposeService `json:"services"`
}

type _StackDetails StackDetails

// NewStackDetails instantiates a new StackDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackDetails(composeFile string, name string, path string, serverId int32, serverName string, services []ComposeService) *StackDetails {
	this := StackDetails{}
	this.ComposeFile = composeFile
	this.Name = name
	this.Path = path
	this.ServerId = serverId
	this.ServerName = serverName
	this.Services = services
	return &this
}

// NewStackDetailsWithDefaults instantiates a new StackDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackDetailsWithDefaults() *StackDetails {
	this := StackDetails{}
	return &this
}

// GetComposeFile returns the ComposeFile field value
func (o *StackDetails) GetComposeFile() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ComposeFile
}

// GetComposeFileOk returns a tuple with the ComposeFile field value
// and a boolean to check if the value has been set.
func (o *StackDetails) GetComposeFileOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ComposeFile, true
}

// SetComposeFile sets field value
func (o *StackDetails) SetComposeFile(v string) {
	o.ComposeFile = v
}

// GetName returns the Name field value
func (o *StackDetails) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *StackDetails) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *StackDetails) SetName(v string) {
	o.Name = v
}

// GetPath returns the Path field value
func (o *StackDetails) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *StackDetails) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *StackDetails) SetPath(v string) {
	o.Path = v
}

// GetServerId returns the ServerId field value
func (o *StackDetails) GetServerId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value
// and a boolean to check if the value has been set.
func (o *StackDetails) GetServerIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerId, true
}

// SetServerId sets field value
func (o *StackDetails) SetServerId(v int32) {
	o.ServerId = v
}

// GetServerName returns the ServerName field value
func (o *StackDetails) GetServerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServerName
}

// GetServerNameOk returns a tuple with the ServerName field value
// and a boolean to check if the value has been set.
func (o *StackDetails) GetServerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerName, true
}

// SetServerName sets field value
func (o *StackDetails) SetServerName(v string) {
	o.ServerName = v
}

// GetServices returns the Services field value
func (o *StackDetails) GetServices() []ComposeService {
	if o == nil {
		var ret []ComposeService
		return ret
	}

	return o.Services
}

// GetServicesOk returns a tuple with the Services field value
// and a boolean to check if the value has been set.
func (o *StackDetails) GetServicesOk() ([]ComposeService, bool) {
	if o == nil {
		return nil, false
	}
	return o.Services, true
}

// SetServices sets field value
func (o *StackDetails) SetServices(v []ComposeService) {
	o.Services = v
}

func (o StackDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["compose_file"] = o.ComposeFile
	toSerialize["name"] = o.Name
	toSerialize["path"] = o.Path
	toSerialize["server_id"] = o.ServerId
	toSerialize["server_name"] = o.ServerName
	toSerialize["services"] = o.Services
	return toSerialize, nil
}

func (o *StackDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"compose_file",
		"name",
		"path",
		"server_id",
		"server_name",
		"services",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStackDetails := _StackDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStackDetails)

	if err != nil {
		return err
	}

	*o = StackDetails(varStackDetails)

	return err
}

type NullableStackDetails struct {
	value *StackDetails
	isSet bool
}

func (v NullableStackDetails) Get() *StackDetails {
	return v.value
}

func (v *NullableStackDetails) Set(val *StackDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableStackDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableStackDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackDetails(val *StackDetails) *NullableStackDetails {
	return &NullableStackDetails{value: val, isSet: true}
}

func (v NullableStackDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


