/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScanWithSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScanWithSummary{}

// ScanWithSummary struct for ScanWithSummary
type ScanWithSummary struct {
	Scan ImageScan `json:"scan"`
	Summary NullableVulnerabilitySummary `json:"summary,omitempty"`
}

type _ScanWithSummary ScanWithSummary

// NewScanWithSummary instantiates a new ScanWithSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScanWithSummary(scan ImageScan) *ScanWithSummary {
	this := ScanWithSummary{}
	this.Scan = scan
	return &this
}

// NewScanWithSummaryWithDefaults instantiates a new ScanWithSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScanWithSummaryWithDefaults() *ScanWithSummary {
	this := ScanWithSummary{}
	return &this
}

// GetScan returns the Scan field value
func (o *ScanWithSummary) GetScan() ImageScan {
	if o == nil {
		var ret ImageScan
		return ret
	}

	return o.Scan
}

// GetScanOk returns a tuple with the Scan field value
// and a boolean to check if the value has been set.
func (o *ScanWithSummary) GetScanOk() (*ImageScan, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Scan, true
}

// SetScan sets field value
func (o *ScanWithSummary) SetScan(v ImageScan) {
	o.Scan = v
}

// GetSummary returns the Summary field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ScanWithSummary) GetSummary() VulnerabilitySummary {
	if o == nil || IsNil(o.Summary.Get()) {
		var ret VulnerabilitySummary
		return ret
	}
	return *o.Summary.Get()
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScanWithSummary) GetSummaryOk() (*VulnerabilitySummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Summary.Get(), o.Summary.IsSet()
}

// HasSummary returns a boolean if a field has been set.
func (o *ScanWithSummary) HasSummary() bool {
	if o != nil && o.Summary.IsSet() {
		return true
	}

	return false
}

// SetSummary gets a reference to the given NullableVulnerabilitySummary and assigns it to the Summary field.
func (o *ScanWithSummary) SetSummary(v VulnerabilitySummary) {
	o.Summary.Set(&v)
}
// SetSummaryNil sets the value for Summary to be an explicit nil
func (o *ScanWithSummary) SetSummaryNil() {
	o.Summary.Set(nil)
}

// UnsetSummary ensures that no value is present for Summary, not even an explicit nil
func (o *ScanWithSummary) UnsetSummary() {
	o.Summary.Unset()
}

func (o ScanWithSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScanWithSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["scan"] = o.Scan
	if o.Summary.IsSet() {
		toSerialize["summary"] = o.Summary.Get()
	}
	return toSerialize, nil
}

func (o *ScanWithSummary) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"scan",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScanWithSummary := _ScanWithSummary{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScanWithSummary)

	if err != nil {
		return err
	}

	*o = ScanWithSummary(varScanWithSummary)

	return err
}

type NullableScanWithSummary struct {
	value *ScanWithSummary
	isSet bool
}

func (v NullableScanWithSummary) Get() *ScanWithSummary {
	return v.value
}

func (v *NullableScanWithSummary) Set(val *ScanWithSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableScanWithSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableScanWithSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScanWithSummary(val *ScanWithSummary) *NullableScanWithSummary {
	return &NullableScanWithSummary{value: val, isSet: true}
}

func (v NullableScanWithSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScanWithSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


