/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Container type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Container{}

// Container struct for Container
type Container struct {
	Command []string `json:"command,omitempty"`
	Created *string `json:"created,omitempty"`
	ExitCode NullableInt32 `json:"exit_code,omitempty"`
	Finished *string `json:"finished,omitempty"`
	Health NullableHealthStatus `json:"health,omitempty"`
	Image string `json:"image"`
	Labels *map[string]string `json:"labels,omitempty"`
	Mounts []ContainerMount `json:"mounts,omitempty"`
	Name string `json:"name"`
	Networks []ContainerNetwork `json:"networks,omitempty"`
	Ports []Port `json:"ports,omitempty"`
	ResourceLimits NullableResourceLimits `json:"resource_limits,omitempty"`
	RestartPolicy NullableRestartPolicy `json:"restart_policy,omitempty"`
	Started *string `json:"started,omitempty"`
	State string `json:"state"`
	User *string `json:"user,omitempty"`
	WorkingDir *string `json:"working_dir,omitempty"`
}

type _Container Container

// NewContainer instantiates a new Container object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainer(image string, name string, state string) *Container {
	this := Container{}
	this.Image = image
	this.Name = name
	this.State = state
	return &this
}

// NewContainerWithDefaults instantiates a new Container object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerWithDefaults() *Container {
	this := Container{}
	return &this
}

// GetCommand returns the Command field value if set, zero value otherwise.
func (o *Container) GetCommand() []string {
	if o == nil || IsNil(o.Command) {
		var ret []string
		return ret
	}
	return o.Command
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetCommandOk() ([]string, bool) {
	if o == nil || IsNil(o.Command) {
		return nil, false
	}
	return o.Command, true
}

// HasCommand returns a boolean if a field has been set.
func (o *Container) HasCommand() bool {
	if o != nil && !IsNil(o.Command) {
		return true
	}

	return false
}

// SetCommand gets a reference to the given []string and assigns it to the Command field.
func (o *Container) SetCommand(v []string) {
	o.Command = v
}

// GetCreated returns the Created field value if set, zero value otherwise.
func (o *Container) GetCreated() string {
	if o == nil || IsNil(o.Created) {
		var ret string
		return ret
	}
	return *o.Created
}

// GetCreatedOk returns a tuple with the Created field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetCreatedOk() (*string, bool) {
	if o == nil || IsNil(o.Created) {
		return nil, false
	}
	return o.Created, true
}

// HasCreated returns a boolean if a field has been set.
func (o *Container) HasCreated() bool {
	if o != nil && !IsNil(o.Created) {
		return true
	}

	return false
}

// SetCreated gets a reference to the given string and assigns it to the Created field.
func (o *Container) SetCreated(v string) {
	o.Created = &v
}

// GetExitCode returns the ExitCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Container) GetExitCode() int32 {
	if o == nil || IsNil(o.ExitCode.Get()) {
		var ret int32
		return ret
	}
	return *o.ExitCode.Get()
}

// GetExitCodeOk returns a tuple with the ExitCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Container) GetExitCodeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExitCode.Get(), o.ExitCode.IsSet()
}

// HasExitCode returns a boolean if a field has been set.
func (o *Container) HasExitCode() bool {
	if o != nil && o.ExitCode.IsSet() {
		return true
	}

	return false
}

// SetExitCode gets a reference to the given NullableInt32 and assigns it to the ExitCode field.
func (o *Container) SetExitCode(v int32) {
	o.ExitCode.Set(&v)
}
// SetExitCodeNil sets the value for ExitCode to be an explicit nil
func (o *Container) SetExitCodeNil() {
	o.ExitCode.Set(nil)
}

// UnsetExitCode ensures that no value is present for ExitCode, not even an explicit nil
func (o *Container) UnsetExitCode() {
	o.ExitCode.Unset()
}

// GetFinished returns the Finished field value if set, zero value otherwise.
func (o *Container) GetFinished() string {
	if o == nil || IsNil(o.Finished) {
		var ret string
		return ret
	}
	return *o.Finished
}

// GetFinishedOk returns a tuple with the Finished field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetFinishedOk() (*string, bool) {
	if o == nil || IsNil(o.Finished) {
		return nil, false
	}
	return o.Finished, true
}

// HasFinished returns a boolean if a field has been set.
func (o *Container) HasFinished() bool {
	if o != nil && !IsNil(o.Finished) {
		return true
	}

	return false
}

// SetFinished gets a reference to the given string and assigns it to the Finished field.
func (o *Container) SetFinished(v string) {
	o.Finished = &v
}

// GetHealth returns the Health field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Container) GetHealth() HealthStatus {
	if o == nil || IsNil(o.Health.Get()) {
		var ret HealthStatus
		return ret
	}
	return *o.Health.Get()
}

// GetHealthOk returns a tuple with the Health field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Container) GetHealthOk() (*HealthStatus, bool) {
	if o == nil {
		return nil, false
	}
	return o.Health.Get(), o.Health.IsSet()
}

// HasHealth returns a boolean if a field has been set.
func (o *Container) HasHealth() bool {
	if o != nil && o.Health.IsSet() {
		return true
	}

	return false
}

// SetHealth gets a reference to the given NullableHealthStatus and assigns it to the Health field.
func (o *Container) SetHealth(v HealthStatus) {
	o.Health.Set(&v)
}
// SetHealthNil sets the value for Health to be an explicit nil
func (o *Container) SetHealthNil() {
	o.Health.Set(nil)
}

// UnsetHealth ensures that no value is present for Health, not even an explicit nil
func (o *Container) UnsetHealth() {
	o.Health.Unset()
}

// GetImage returns the Image field value
func (o *Container) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *Container) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *Container) SetImage(v string) {
	o.Image = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *Container) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *Container) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *Container) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetMounts returns the Mounts field value if set, zero value otherwise.
func (o *Container) GetMounts() []ContainerMount {
	if o == nil || IsNil(o.Mounts) {
		var ret []ContainerMount
		return ret
	}
	return o.Mounts
}

// GetMountsOk returns a tuple with the Mounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetMountsOk() ([]ContainerMount, bool) {
	if o == nil || IsNil(o.Mounts) {
		return nil, false
	}
	return o.Mounts, true
}

// HasMounts returns a boolean if a field has been set.
func (o *Container) HasMounts() bool {
	if o != nil && !IsNil(o.Mounts) {
		return true
	}

	return false
}

// SetMounts gets a reference to the given []ContainerMount and assigns it to the Mounts field.
func (o *Container) SetMounts(v []ContainerMount) {
	o.Mounts = v
}

// GetName returns the Name field value
func (o *Container) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Container) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Container) SetName(v string) {
	o.Name = v
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *Container) GetNetworks() []ContainerNetwork {
	if o == nil || IsNil(o.Networks) {
		var ret []ContainerNetwork
		return ret
	}
	return o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetNetworksOk() ([]ContainerNetwork, bool) {
	if o == nil || IsNil(o.Networks) {
		return nil, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *Container) HasNetworks() bool {
	if o != nil && !IsNil(o.Networks) {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given []ContainerNetwork and assigns it to the Networks field.
func (o *Container) SetNetworks(v []ContainerNetwork) {
	o.Networks = v
}

// GetPorts returns the Ports field value if set, zero value otherwise.
func (o *Container) GetPorts() []Port {
	if o == nil || IsNil(o.Ports) {
		var ret []Port
		return ret
	}
	return o.Ports
}

// GetPortsOk returns a tuple with the Ports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetPortsOk() ([]Port, bool) {
	if o == nil || IsNil(o.Ports) {
		return nil, false
	}
	return o.Ports, true
}

// HasPorts returns a boolean if a field has been set.
func (o *Container) HasPorts() bool {
	if o != nil && !IsNil(o.Ports) {
		return true
	}

	return false
}

// SetPorts gets a reference to the given []Port and assigns it to the Ports field.
func (o *Container) SetPorts(v []Port) {
	o.Ports = v
}

// GetResourceLimits returns the ResourceLimits field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Container) GetResourceLimits() ResourceLimits {
	if o == nil || IsNil(o.ResourceLimits.Get()) {
		var ret ResourceLimits
		return ret
	}
	return *o.ResourceLimits.Get()
}

// GetResourceLimitsOk returns a tuple with the ResourceLimits field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Container) GetResourceLimitsOk() (*ResourceLimits, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceLimits.Get(), o.ResourceLimits.IsSet()
}

// HasResourceLimits returns a boolean if a field has been set.
func (o *Container) HasResourceLimits() bool {
	if o != nil && o.ResourceLimits.IsSet() {
		return true
	}

	return false
}

// SetResourceLimits gets a reference to the given NullableResourceLimits and assigns it to the ResourceLimits field.
func (o *Container) SetResourceLimits(v ResourceLimits) {
	o.ResourceLimits.Set(&v)
}
// SetResourceLimitsNil sets the value for ResourceLimits to be an explicit nil
func (o *Container) SetResourceLimitsNil() {
	o.ResourceLimits.Set(nil)
}

// UnsetResourceLimits ensures that no value is present for ResourceLimits, not even an explicit nil
func (o *Container) UnsetResourceLimits() {
	o.ResourceLimits.Unset()
}

// GetRestartPolicy returns the RestartPolicy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *Container) GetRestartPolicy() RestartPolicy {
	if o == nil || IsNil(o.RestartPolicy.Get()) {
		var ret RestartPolicy
		return ret
	}
	return *o.RestartPolicy.Get()
}

// GetRestartPolicyOk returns a tuple with the RestartPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *Container) GetRestartPolicyOk() (*RestartPolicy, bool) {
	if o == nil {
		return nil, false
	}
	return o.RestartPolicy.Get(), o.RestartPolicy.IsSet()
}

// HasRestartPolicy returns a boolean if a field has been set.
func (o *Container) HasRestartPolicy() bool {
	if o != nil && o.RestartPolicy.IsSet() {
		return true
	}

	return false
}

// SetRestartPolicy gets a reference to the given NullableRestartPolicy and assigns it to the RestartPolicy field.
func (o *Container) SetRestartPolicy(v RestartPolicy) {
	o.RestartPolicy.Set(&v)
}
// SetRestartPolicyNil sets the value for RestartPolicy to be an explicit nil
func (o *Container) SetRestartPolicyNil() {
	o.RestartPolicy.Set(nil)
}

// UnsetRestartPolicy ensures that no value is present for RestartPolicy, not even an explicit nil
func (o *Container) UnsetRestartPolicy() {
	o.RestartPolicy.Unset()
}

// GetStarted returns the Started field value if set, zero value otherwise.
func (o *Container) GetStarted() string {
	if o == nil || IsNil(o.Started) {
		var ret string
		return ret
	}
	return *o.Started
}

// GetStartedOk returns a tuple with the Started field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetStartedOk() (*string, bool) {
	if o == nil || IsNil(o.Started) {
		return nil, false
	}
	return o.Started, true
}

// HasStarted returns a boolean if a field has been set.
func (o *Container) HasStarted() bool {
	if o != nil && !IsNil(o.Started) {
		return true
	}

	return false
}

// SetStarted gets a reference to the given string and assigns it to the Started field.
func (o *Container) SetStarted(v string) {
	o.Started = &v
}

// GetState returns the State field value
func (o *Container) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *Container) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *Container) SetState(v string) {
	o.State = v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *Container) GetUser() string {
	if o == nil || IsNil(o.User) {
		var ret string
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetUserOk() (*string, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *Container) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given string and assigns it to the User field.
func (o *Container) SetUser(v string) {
	o.User = &v
}

// GetWorkingDir returns the WorkingDir field value if set, zero value otherwise.
func (o *Container) GetWorkingDir() string {
	if o == nil || IsNil(o.WorkingDir) {
		var ret string
		return ret
	}
	return *o.WorkingDir
}

// GetWorkingDirOk returns a tuple with the WorkingDir field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Container) GetWorkingDirOk() (*string, bool) {
	if o == nil || IsNil(o.WorkingDir) {
		return nil, false
	}
	return o.WorkingDir, true
}

// HasWorkingDir returns a boolean if a field has been set.
func (o *Container) HasWorkingDir() bool {
	if o != nil && !IsNil(o.WorkingDir) {
		return true
	}

	return false
}

// SetWorkingDir gets a reference to the given string and assigns it to the WorkingDir field.
func (o *Container) SetWorkingDir(v string) {
	o.WorkingDir = &v
}

func (o Container) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Container) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Command) {
		toSerialize["command"] = o.Command
	}
	if !IsNil(o.Created) {
		toSerialize["created"] = o.Created
	}
	if o.ExitCode.IsSet() {
		toSerialize["exit_code"] = o.ExitCode.Get()
	}
	if !IsNil(o.Finished) {
		toSerialize["finished"] = o.Finished
	}
	if o.Health.IsSet() {
		toSerialize["health"] = o.Health.Get()
	}
	toSerialize["image"] = o.Image
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Mounts) {
		toSerialize["mounts"] = o.Mounts
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	if !IsNil(o.Ports) {
		toSerialize["ports"] = o.Ports
	}
	if o.ResourceLimits.IsSet() {
		toSerialize["resource_limits"] = o.ResourceLimits.Get()
	}
	if o.RestartPolicy.IsSet() {
		toSerialize["restart_policy"] = o.RestartPolicy.Get()
	}
	if !IsNil(o.Started) {
		toSerialize["started"] = o.Started
	}
	toSerialize["state"] = o.State
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.WorkingDir) {
		toSerialize["working_dir"] = o.WorkingDir
	}
	return toSerialize, nil
}

func (o *Container) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image",
		"name",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainer := _Container{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainer)

	if err != nil {
		return err
	}

	*o = Container(varContainer)

	return err
}

type NullableContainer struct {
	value *Container
	isSet bool
}

func (v NullableContainer) Get() *Container {
	return v.value
}

func (v *NullableContainer) Set(val *Container) {
	v.value = val
	v.isSet = true
}

func (v NullableContainer) IsSet() bool {
	return v.isSet
}

func (v *NullableContainer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainer(val *Container) *NullableContainer {
	return &NullableContainer{value: val, isSet: true}
}

func (v NullableContainer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


