/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdminDeleteServerResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminDeleteServerResponseData{}

// AdminDeleteServerResponseData struct for AdminDeleteServerResponseData
type AdminDeleteServerResponseData struct {
	Message string `json:"message"`
}

type _AdminDeleteServerResponseData AdminDeleteServerResponseData

// NewAdminDeleteServerResponseData instantiates a new AdminDeleteServerResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminDeleteServerResponseData(message string) *AdminDeleteServerResponseData {
	this := AdminDeleteServerResponseData{}
	this.Message = message
	return &this
}

// NewAdminDeleteServerResponseDataWithDefaults instantiates a new AdminDeleteServerResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminDeleteServerResponseDataWithDefaults() *AdminDeleteServerResponseData {
	this := AdminDeleteServerResponseData{}
	return &this
}

// GetMessage returns the Message field value
func (o *AdminDeleteServerResponseData) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *AdminDeleteServerResponseData) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *AdminDeleteServerResponseData) SetMessage(v string) {
	o.Message = v
}

func (o AdminDeleteServerResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminDeleteServerResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *AdminDeleteServerResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminDeleteServerResponseData := _AdminDeleteServerResponseData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdminDeleteServerResponseData)

	if err != nil {
		return err
	}

	*o = AdminDeleteServerResponseData(varAdminDeleteServerResponseData)

	return err
}

type NullableAdminDeleteServerResponseData struct {
	value *AdminDeleteServerResponseData
	isSet bool
}

func (v NullableAdminDeleteServerResponseData) Get() *AdminDeleteServerResponseData {
	return v.value
}

func (v *NullableAdminDeleteServerResponseData) Set(val *AdminDeleteServerResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminDeleteServerResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminDeleteServerResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminDeleteServerResponseData(val *AdminDeleteServerResponseData) *NullableAdminDeleteServerResponseData {
	return &NullableAdminDeleteServerResponseData{value: val, isSet: true}
}

func (v NullableAdminDeleteServerResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminDeleteServerResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


