/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ServerUpdateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerUpdateRequest{}

// ServerUpdateRequest struct for ServerUpdateRequest
type ServerUpdateRequest struct {
	AccessToken string `json:"access_token"`
	Description string `json:"description"`
	Host string `json:"host"`
	IsActive bool `json:"is_active"`
	Name string `json:"name"`
	Port int32 `json:"port"`
	SkipSslVerification NullableBool `json:"skip_ssl_verification"`
}

type _ServerUpdateRequest ServerUpdateRequest

// NewServerUpdateRequest instantiates a new ServerUpdateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerUpdateRequest(accessToken string, description string, host string, isActive bool, name string, port int32, skipSslVerification NullableBool) *ServerUpdateRequest {
	this := ServerUpdateRequest{}
	this.AccessToken = accessToken
	this.Description = description
	this.Host = host
	this.IsActive = isActive
	this.Name = name
	this.Port = port
	this.SkipSslVerification = skipSslVerification
	return &this
}

// NewServerUpdateRequestWithDefaults instantiates a new ServerUpdateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerUpdateRequestWithDefaults() *ServerUpdateRequest {
	this := ServerUpdateRequest{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *ServerUpdateRequest) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *ServerUpdateRequest) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *ServerUpdateRequest) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetDescription returns the Description field value
func (o *ServerUpdateRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ServerUpdateRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ServerUpdateRequest) SetDescription(v string) {
	o.Description = v
}

// GetHost returns the Host field value
func (o *ServerUpdateRequest) GetHost() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Host
}

// GetHostOk returns a tuple with the Host field value
// and a boolean to check if the value has been set.
func (o *ServerUpdateRequest) GetHostOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Host, true
}

// SetHost sets field value
func (o *ServerUpdateRequest) SetHost(v string) {
	o.Host = v
}

// GetIsActive returns the IsActive field value
func (o *ServerUpdateRequest) GetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value
// and a boolean to check if the value has been set.
func (o *ServerUpdateRequest) GetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsActive, true
}

// SetIsActive sets field value
func (o *ServerUpdateRequest) SetIsActive(v bool) {
	o.IsActive = v
}

// GetName returns the Name field value
func (o *ServerUpdateRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServerUpdateRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServerUpdateRequest) SetName(v string) {
	o.Name = v
}

// GetPort returns the Port field value
func (o *ServerUpdateRequest) GetPort() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Port
}

// GetPortOk returns a tuple with the Port field value
// and a boolean to check if the value has been set.
func (o *ServerUpdateRequest) GetPortOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Port, true
}

// SetPort sets field value
func (o *ServerUpdateRequest) SetPort(v int32) {
	o.Port = v
}

// GetSkipSslVerification returns the SkipSslVerification field value
// If the value is explicit nil, the zero value for bool will be returned
func (o *ServerUpdateRequest) GetSkipSslVerification() bool {
	if o == nil || o.SkipSslVerification.Get() == nil {
		var ret bool
		return ret
	}

	return *o.SkipSslVerification.Get()
}

// GetSkipSslVerificationOk returns a tuple with the SkipSslVerification field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServerUpdateRequest) GetSkipSslVerificationOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.SkipSslVerification.Get(), o.SkipSslVerification.IsSet()
}

// SetSkipSslVerification sets field value
func (o *ServerUpdateRequest) SetSkipSslVerification(v bool) {
	o.SkipSslVerification.Set(&v)
}

func (o ServerUpdateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerUpdateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["description"] = o.Description
	toSerialize["host"] = o.Host
	toSerialize["is_active"] = o.IsActive
	toSerialize["name"] = o.Name
	toSerialize["port"] = o.Port
	toSerialize["skip_ssl_verification"] = o.SkipSslVerification.Get()
	return toSerialize, nil
}

func (o *ServerUpdateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"description",
		"host",
		"is_active",
		"name",
		"port",
		"skip_ssl_verification",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServerUpdateRequest := _ServerUpdateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varServerUpdateRequest)

	if err != nil {
		return err
	}

	*o = ServerUpdateRequest(varServerUpdateRequest)

	return err
}

type NullableServerUpdateRequest struct {
	value *ServerUpdateRequest
	isSet bool
}

func (v NullableServerUpdateRequest) Get() *ServerUpdateRequest {
	return v.value
}

func (v *NullableServerUpdateRequest) Set(val *ServerUpdateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableServerUpdateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableServerUpdateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerUpdateRequest(val *ServerUpdateRequest) *NullableServerUpdateRequest {
	return &NullableServerUpdateRequest{value: val, isSet: true}
}

func (v NullableServerUpdateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerUpdateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


