/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCredentialRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCredentialRequest{}

// UpdateCredentialRequest struct for UpdateCredentialRequest
type UpdateCredentialRequest struct {
	ImagePattern string `json:"image_pattern"`
	Password string `json:"password"`
	RegistryUrl string `json:"registry_url"`
	StackPattern string `json:"stack_pattern"`
	Username string `json:"username"`
}

type _UpdateCredentialRequest UpdateCredentialRequest

// NewUpdateCredentialRequest instantiates a new UpdateCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCredentialRequest(imagePattern string, password string, registryUrl string, stackPattern string, username string) *UpdateCredentialRequest {
	this := UpdateCredentialRequest{}
	this.ImagePattern = imagePattern
	this.Password = password
	this.RegistryUrl = registryUrl
	this.StackPattern = stackPattern
	this.Username = username
	return &this
}

// NewUpdateCredentialRequestWithDefaults instantiates a new UpdateCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCredentialRequestWithDefaults() *UpdateCredentialRequest {
	this := UpdateCredentialRequest{}
	return &this
}

// GetImagePattern returns the ImagePattern field value
func (o *UpdateCredentialRequest) GetImagePattern() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImagePattern
}

// GetImagePatternOk returns a tuple with the ImagePattern field value
// and a boolean to check if the value has been set.
func (o *UpdateCredentialRequest) GetImagePatternOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImagePattern, true
}

// SetImagePattern sets field value
func (o *UpdateCredentialRequest) SetImagePattern(v string) {
	o.ImagePattern = v
}

// GetPassword returns the Password field value
func (o *UpdateCredentialRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *UpdateCredentialRequest) GetPasswordOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *UpdateCredentialRequest) SetPassword(v string) {
	o.Password = v
}

// GetRegistryUrl returns the RegistryUrl field value
func (o *UpdateCredentialRequest) GetRegistryUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RegistryUrl
}

// GetRegistryUrlOk returns a tuple with the RegistryUrl field value
// and a boolean to check if the value has been set.
func (o *UpdateCredentialRequest) GetRegistryUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegistryUrl, true
}

// SetRegistryUrl sets field value
func (o *UpdateCredentialRequest) SetRegistryUrl(v string) {
	o.RegistryUrl = v
}

// GetStackPattern returns the StackPattern field value
func (o *UpdateCredentialRequest) GetStackPattern() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StackPattern
}

// GetStackPatternOk returns a tuple with the StackPattern field value
// and a boolean to check if the value has been set.
func (o *UpdateCredentialRequest) GetStackPatternOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StackPattern, true
}

// SetStackPattern sets field value
func (o *UpdateCredentialRequest) SetStackPattern(v string) {
	o.StackPattern = v
}

// GetUsername returns the Username field value
func (o *UpdateCredentialRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *UpdateCredentialRequest) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *UpdateCredentialRequest) SetUsername(v string) {
	o.Username = v
}

func (o UpdateCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCredentialRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["image_pattern"] = o.ImagePattern
	toSerialize["password"] = o.Password
	toSerialize["registry_url"] = o.RegistryUrl
	toSerialize["stack_pattern"] = o.StackPattern
	toSerialize["username"] = o.Username
	return toSerialize, nil
}

func (o *UpdateCredentialRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image_pattern",
		"password",
		"registry_url",
		"stack_pattern",
		"username",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCredentialRequest := _UpdateCredentialRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCredentialRequest)

	if err != nil {
		return err
	}

	*o = UpdateCredentialRequest(varUpdateCredentialRequest)

	return err
}

type NullableUpdateCredentialRequest struct {
	value *UpdateCredentialRequest
	isSet bool
}

func (v NullableUpdateCredentialRequest) Get() *UpdateCredentialRequest {
	return v.value
}

func (v *NullableUpdateCredentialRequest) Set(val *UpdateCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCredentialRequest(val *UpdateCredentialRequest) *NullableUpdateCredentialRequest {
	return &NullableUpdateCredentialRequest{value: val, isSet: true}
}

func (v NullableUpdateCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


