/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ImageScan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ImageScan{}

// ImageScan struct for ImageScan
type ImageScan struct {
	AgentScanId string `json:"agent_scan_id"`
	CompletedAt NullableTime `json:"completed_at,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	DeletedAt *DeletedAt `json:"deleted_at,omitempty"`
	ErrorMessage *string `json:"error_message,omitempty"`
	Id int32 `json:"id"`
	LastPollError *string `json:"last_poll_error,omitempty"`
	LastPolledAt NullableTime `json:"last_polled_at,omitempty"`
	PollFailures int32 `json:"poll_failures"`
	ScannedImages int32 `json:"scanned_images"`
	Scopes []ScanScope `json:"scopes,omitempty"`
	ServerId int32 `json:"server_id"`
	ServiceFilter *string `json:"service_filter,omitempty"`
	StackName string `json:"stack_name"`
	StartedAt time.Time `json:"started_at"`
	Status string `json:"status"`
	TotalImages int32 `json:"total_images"`
	UpdatedAt time.Time `json:"updated_at"`
	Vulnerabilities []ImageVulnerability `json:"vulnerabilities,omitempty"`
}

type _ImageScan ImageScan

// NewImageScan instantiates a new ImageScan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewImageScan(agentScanId string, createdAt time.Time, id int32, pollFailures int32, scannedImages int32, serverId int32, stackName string, startedAt time.Time, status string, totalImages int32, updatedAt time.Time) *ImageScan {
	this := ImageScan{}
	this.AgentScanId = agentScanId
	this.CreatedAt = createdAt
	this.Id = id
	this.PollFailures = pollFailures
	this.ScannedImages = scannedImages
	this.ServerId = serverId
	this.StackName = stackName
	this.StartedAt = startedAt
	this.Status = status
	this.TotalImages = totalImages
	this.UpdatedAt = updatedAt
	return &this
}

// NewImageScanWithDefaults instantiates a new ImageScan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewImageScanWithDefaults() *ImageScan {
	this := ImageScan{}
	return &this
}

// GetAgentScanId returns the AgentScanId field value
func (o *ImageScan) GetAgentScanId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentScanId
}

// GetAgentScanIdOk returns a tuple with the AgentScanId field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetAgentScanIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentScanId, true
}

// SetAgentScanId sets field value
func (o *ImageScan) SetAgentScanId(v string) {
	o.AgentScanId = v
}

// GetCompletedAt returns the CompletedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ImageScan) GetCompletedAt() time.Time {
	if o == nil || IsNil(o.CompletedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.CompletedAt.Get()
}

// GetCompletedAtOk returns a tuple with the CompletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageScan) GetCompletedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompletedAt.Get(), o.CompletedAt.IsSet()
}

// HasCompletedAt returns a boolean if a field has been set.
func (o *ImageScan) HasCompletedAt() bool {
	if o != nil && o.CompletedAt.IsSet() {
		return true
	}

	return false
}

// SetCompletedAt gets a reference to the given NullableTime and assigns it to the CompletedAt field.
func (o *ImageScan) SetCompletedAt(v time.Time) {
	o.CompletedAt.Set(&v)
}
// SetCompletedAtNil sets the value for CompletedAt to be an explicit nil
func (o *ImageScan) SetCompletedAtNil() {
	o.CompletedAt.Set(nil)
}

// UnsetCompletedAt ensures that no value is present for CompletedAt, not even an explicit nil
func (o *ImageScan) UnsetCompletedAt() {
	o.CompletedAt.Unset()
}

// GetCreatedAt returns the CreatedAt field value
func (o *ImageScan) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ImageScan) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *ImageScan) GetDeletedAt() DeletedAt {
	if o == nil || IsNil(o.DeletedAt) {
		var ret DeletedAt
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageScan) GetDeletedAtOk() (*DeletedAt, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *ImageScan) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given DeletedAt and assigns it to the DeletedAt field.
func (o *ImageScan) SetDeletedAt(v DeletedAt) {
	o.DeletedAt = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *ImageScan) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageScan) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *ImageScan) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *ImageScan) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetId returns the Id field value
func (o *ImageScan) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ImageScan) SetId(v int32) {
	o.Id = v
}

// GetLastPollError returns the LastPollError field value if set, zero value otherwise.
func (o *ImageScan) GetLastPollError() string {
	if o == nil || IsNil(o.LastPollError) {
		var ret string
		return ret
	}
	return *o.LastPollError
}

// GetLastPollErrorOk returns a tuple with the LastPollError field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageScan) GetLastPollErrorOk() (*string, bool) {
	if o == nil || IsNil(o.LastPollError) {
		return nil, false
	}
	return o.LastPollError, true
}

// HasLastPollError returns a boolean if a field has been set.
func (o *ImageScan) HasLastPollError() bool {
	if o != nil && !IsNil(o.LastPollError) {
		return true
	}

	return false
}

// SetLastPollError gets a reference to the given string and assigns it to the LastPollError field.
func (o *ImageScan) SetLastPollError(v string) {
	o.LastPollError = &v
}

// GetLastPolledAt returns the LastPolledAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ImageScan) GetLastPolledAt() time.Time {
	if o == nil || IsNil(o.LastPolledAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastPolledAt.Get()
}

// GetLastPolledAtOk returns a tuple with the LastPolledAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ImageScan) GetLastPolledAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastPolledAt.Get(), o.LastPolledAt.IsSet()
}

// HasLastPolledAt returns a boolean if a field has been set.
func (o *ImageScan) HasLastPolledAt() bool {
	if o != nil && o.LastPolledAt.IsSet() {
		return true
	}

	return false
}

// SetLastPolledAt gets a reference to the given NullableTime and assigns it to the LastPolledAt field.
func (o *ImageScan) SetLastPolledAt(v time.Time) {
	o.LastPolledAt.Set(&v)
}
// SetLastPolledAtNil sets the value for LastPolledAt to be an explicit nil
func (o *ImageScan) SetLastPolledAtNil() {
	o.LastPolledAt.Set(nil)
}

// UnsetLastPolledAt ensures that no value is present for LastPolledAt, not even an explicit nil
func (o *ImageScan) UnsetLastPolledAt() {
	o.LastPolledAt.Unset()
}

// GetPollFailures returns the PollFailures field value
func (o *ImageScan) GetPollFailures() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PollFailures
}

// GetPollFailuresOk returns a tuple with the PollFailures field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetPollFailuresOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PollFailures, true
}

// SetPollFailures sets field value
func (o *ImageScan) SetPollFailures(v int32) {
	o.PollFailures = v
}

// GetScannedImages returns the ScannedImages field value
func (o *ImageScan) GetScannedImages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ScannedImages
}

// GetScannedImagesOk returns a tuple with the ScannedImages field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetScannedImagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScannedImages, true
}

// SetScannedImages sets field value
func (o *ImageScan) SetScannedImages(v int32) {
	o.ScannedImages = v
}

// GetScopes returns the Scopes field value if set, zero value otherwise.
func (o *ImageScan) GetScopes() []ScanScope {
	if o == nil || IsNil(o.Scopes) {
		var ret []ScanScope
		return ret
	}
	return o.Scopes
}

// GetScopesOk returns a tuple with the Scopes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageScan) GetScopesOk() ([]ScanScope, bool) {
	if o == nil || IsNil(o.Scopes) {
		return nil, false
	}
	return o.Scopes, true
}

// HasScopes returns a boolean if a field has been set.
func (o *ImageScan) HasScopes() bool {
	if o != nil && !IsNil(o.Scopes) {
		return true
	}

	return false
}

// SetScopes gets a reference to the given []ScanScope and assigns it to the Scopes field.
func (o *ImageScan) SetScopes(v []ScanScope) {
	o.Scopes = v
}

// GetServerId returns the ServerId field value
func (o *ImageScan) GetServerId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetServerIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerId, true
}

// SetServerId sets field value
func (o *ImageScan) SetServerId(v int32) {
	o.ServerId = v
}

// GetServiceFilter returns the ServiceFilter field value if set, zero value otherwise.
func (o *ImageScan) GetServiceFilter() string {
	if o == nil || IsNil(o.ServiceFilter) {
		var ret string
		return ret
	}
	return *o.ServiceFilter
}

// GetServiceFilterOk returns a tuple with the ServiceFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageScan) GetServiceFilterOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceFilter) {
		return nil, false
	}
	return o.ServiceFilter, true
}

// HasServiceFilter returns a boolean if a field has been set.
func (o *ImageScan) HasServiceFilter() bool {
	if o != nil && !IsNil(o.ServiceFilter) {
		return true
	}

	return false
}

// SetServiceFilter gets a reference to the given string and assigns it to the ServiceFilter field.
func (o *ImageScan) SetServiceFilter(v string) {
	o.ServiceFilter = &v
}

// GetStackName returns the StackName field value
func (o *ImageScan) GetStackName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StackName
}

// GetStackNameOk returns a tuple with the StackName field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetStackNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StackName, true
}

// SetStackName sets field value
func (o *ImageScan) SetStackName(v string) {
	o.StackName = v
}

// GetStartedAt returns the StartedAt field value
func (o *ImageScan) GetStartedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetStartedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartedAt, true
}

// SetStartedAt sets field value
func (o *ImageScan) SetStartedAt(v time.Time) {
	o.StartedAt = v
}

// GetStatus returns the Status field value
func (o *ImageScan) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ImageScan) SetStatus(v string) {
	o.Status = v
}

// GetTotalImages returns the TotalImages field value
func (o *ImageScan) GetTotalImages() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalImages
}

// GetTotalImagesOk returns a tuple with the TotalImages field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetTotalImagesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalImages, true
}

// SetTotalImages sets field value
func (o *ImageScan) SetTotalImages(v int32) {
	o.TotalImages = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ImageScan) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ImageScan) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ImageScan) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetVulnerabilities returns the Vulnerabilities field value if set, zero value otherwise.
func (o *ImageScan) GetVulnerabilities() []ImageVulnerability {
	if o == nil || IsNil(o.Vulnerabilities) {
		var ret []ImageVulnerability
		return ret
	}
	return o.Vulnerabilities
}

// GetVulnerabilitiesOk returns a tuple with the Vulnerabilities field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ImageScan) GetVulnerabilitiesOk() ([]ImageVulnerability, bool) {
	if o == nil || IsNil(o.Vulnerabilities) {
		return nil, false
	}
	return o.Vulnerabilities, true
}

// HasVulnerabilities returns a boolean if a field has been set.
func (o *ImageScan) HasVulnerabilities() bool {
	if o != nil && !IsNil(o.Vulnerabilities) {
		return true
	}

	return false
}

// SetVulnerabilities gets a reference to the given []ImageVulnerability and assigns it to the Vulnerabilities field.
func (o *ImageScan) SetVulnerabilities(v []ImageVulnerability) {
	o.Vulnerabilities = v
}

func (o ImageScan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ImageScan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["agent_scan_id"] = o.AgentScanId
	if o.CompletedAt.IsSet() {
		toSerialize["completed_at"] = o.CompletedAt.Get()
	}
	toSerialize["created_at"] = o.CreatedAt
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["error_message"] = o.ErrorMessage
	}
	toSerialize["id"] = o.Id
	if !IsNil(o.LastPollError) {
		toSerialize["last_poll_error"] = o.LastPollError
	}
	if o.LastPolledAt.IsSet() {
		toSerialize["last_polled_at"] = o.LastPolledAt.Get()
	}
	toSerialize["poll_failures"] = o.PollFailures
	toSerialize["scanned_images"] = o.ScannedImages
	if !IsNil(o.Scopes) {
		toSerialize["scopes"] = o.Scopes
	}
	toSerialize["server_id"] = o.ServerId
	if !IsNil(o.ServiceFilter) {
		toSerialize["service_filter"] = o.ServiceFilter
	}
	toSerialize["stack_name"] = o.StackName
	toSerialize["started_at"] = o.StartedAt
	toSerialize["status"] = o.Status
	toSerialize["total_images"] = o.TotalImages
	toSerialize["updated_at"] = o.UpdatedAt
	if !IsNil(o.Vulnerabilities) {
		toSerialize["vulnerabilities"] = o.Vulnerabilities
	}
	return toSerialize, nil
}

func (o *ImageScan) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"agent_scan_id",
		"created_at",
		"id",
		"poll_failures",
		"scanned_images",
		"server_id",
		"stack_name",
		"started_at",
		"status",
		"total_images",
		"updated_at",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varImageScan := _ImageScan{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varImageScan)

	if err != nil {
		return err
	}

	*o = ImageScan(varImageScan)

	return err
}

type NullableImageScan struct {
	value *ImageScan
	isSet bool
}

func (v NullableImageScan) Get() *ImageScan {
	return v.value
}

func (v *NullableImageScan) Set(val *ImageScan) {
	v.value = val
	v.isSet = true
}

func (v NullableImageScan) IsSet() bool {
	return v.isSet
}

func (v *NullableImageScan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableImageScan(val *ImageScan) *NullableImageScan {
	return &NullableImageScan{value: val, isSet: true}
}

func (v NullableImageScan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableImageScan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


