/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthRefreshData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthRefreshData{}

// AuthRefreshData struct for AuthRefreshData
type AuthRefreshData struct {
	AccessToken string `json:"access_token"`
	ExpiresIn int32 `json:"expires_in"`
	RefreshExpiresIn int32 `json:"refresh_expires_in"`
	RefreshToken string `json:"refresh_token"`
	TokenType string `json:"token_type"`
}

type _AuthRefreshData AuthRefreshData

// NewAuthRefreshData instantiates a new AuthRefreshData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthRefreshData(accessToken string, expiresIn int32, refreshExpiresIn int32, refreshToken string, tokenType string) *AuthRefreshData {
	this := AuthRefreshData{}
	this.AccessToken = accessToken
	this.ExpiresIn = expiresIn
	this.RefreshExpiresIn = refreshExpiresIn
	this.RefreshToken = refreshToken
	this.TokenType = tokenType
	return &this
}

// NewAuthRefreshDataWithDefaults instantiates a new AuthRefreshData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthRefreshDataWithDefaults() *AuthRefreshData {
	this := AuthRefreshData{}
	return &this
}

// GetAccessToken returns the AccessToken field value
func (o *AuthRefreshData) GetAccessToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value
// and a boolean to check if the value has been set.
func (o *AuthRefreshData) GetAccessTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessToken, true
}

// SetAccessToken sets field value
func (o *AuthRefreshData) SetAccessToken(v string) {
	o.AccessToken = v
}

// GetExpiresIn returns the ExpiresIn field value
func (o *AuthRefreshData) GetExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiresIn
}

// GetExpiresInOk returns a tuple with the ExpiresIn field value
// and a boolean to check if the value has been set.
func (o *AuthRefreshData) GetExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresIn, true
}

// SetExpiresIn sets field value
func (o *AuthRefreshData) SetExpiresIn(v int32) {
	o.ExpiresIn = v
}

// GetRefreshExpiresIn returns the RefreshExpiresIn field value
func (o *AuthRefreshData) GetRefreshExpiresIn() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RefreshExpiresIn
}

// GetRefreshExpiresInOk returns a tuple with the RefreshExpiresIn field value
// and a boolean to check if the value has been set.
func (o *AuthRefreshData) GetRefreshExpiresInOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshExpiresIn, true
}

// SetRefreshExpiresIn sets field value
func (o *AuthRefreshData) SetRefreshExpiresIn(v int32) {
	o.RefreshExpiresIn = v
}

// GetRefreshToken returns the RefreshToken field value
func (o *AuthRefreshData) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *AuthRefreshData) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *AuthRefreshData) SetRefreshToken(v string) {
	o.RefreshToken = v
}

// GetTokenType returns the TokenType field value
func (o *AuthRefreshData) GetTokenType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenType
}

// GetTokenTypeOk returns a tuple with the TokenType field value
// and a boolean to check if the value has been set.
func (o *AuthRefreshData) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenType, true
}

// SetTokenType sets field value
func (o *AuthRefreshData) SetTokenType(v string) {
	o.TokenType = v
}

func (o AuthRefreshData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthRefreshData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["access_token"] = o.AccessToken
	toSerialize["expires_in"] = o.ExpiresIn
	toSerialize["refresh_expires_in"] = o.RefreshExpiresIn
	toSerialize["refresh_token"] = o.RefreshToken
	toSerialize["token_type"] = o.TokenType
	return toSerialize, nil
}

func (o *AuthRefreshData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"access_token",
		"expires_in",
		"refresh_expires_in",
		"refresh_token",
		"token_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthRefreshData := _AuthRefreshData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthRefreshData)

	if err != nil {
		return err
	}

	*o = AuthRefreshData(varAuthRefreshData)

	return err
}

type NullableAuthRefreshData struct {
	value *AuthRefreshData
	isSet bool
}

func (v NullableAuthRefreshData) Get() *AuthRefreshData {
	return v.value
}

func (v *NullableAuthRefreshData) Set(val *AuthRefreshData) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthRefreshData) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthRefreshData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthRefreshData(val *AuthRefreshData) *NullableAuthRefreshData {
	return &NullableAuthRefreshData{value: val, isSet: true}
}

func (v NullableAuthRefreshData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthRefreshData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


