/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RestartPolicy type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestartPolicy{}

// RestartPolicy struct for RestartPolicy
type RestartPolicy struct {
	MaximumRetryCount *int32 `json:"maximum_retry_count,omitempty"`
	Name string `json:"name"`
}

type _RestartPolicy RestartPolicy

// NewRestartPolicy instantiates a new RestartPolicy object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestartPolicy(name string) *RestartPolicy {
	this := RestartPolicy{}
	this.Name = name
	return &this
}

// NewRestartPolicyWithDefaults instantiates a new RestartPolicy object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestartPolicyWithDefaults() *RestartPolicy {
	this := RestartPolicy{}
	return &this
}

// GetMaximumRetryCount returns the MaximumRetryCount field value if set, zero value otherwise.
func (o *RestartPolicy) GetMaximumRetryCount() int32 {
	if o == nil || IsNil(o.MaximumRetryCount) {
		var ret int32
		return ret
	}
	return *o.MaximumRetryCount
}

// GetMaximumRetryCountOk returns a tuple with the MaximumRetryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestartPolicy) GetMaximumRetryCountOk() (*int32, bool) {
	if o == nil || IsNil(o.MaximumRetryCount) {
		return nil, false
	}
	return o.MaximumRetryCount, true
}

// HasMaximumRetryCount returns a boolean if a field has been set.
func (o *RestartPolicy) HasMaximumRetryCount() bool {
	if o != nil && !IsNil(o.MaximumRetryCount) {
		return true
	}

	return false
}

// SetMaximumRetryCount gets a reference to the given int32 and assigns it to the MaximumRetryCount field.
func (o *RestartPolicy) SetMaximumRetryCount(v int32) {
	o.MaximumRetryCount = &v
}

// GetName returns the Name field value
func (o *RestartPolicy) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RestartPolicy) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RestartPolicy) SetName(v string) {
	o.Name = v
}

func (o RestartPolicy) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestartPolicy) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaximumRetryCount) {
		toSerialize["maximum_retry_count"] = o.MaximumRetryCount
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *RestartPolicy) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestartPolicy := _RestartPolicy{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRestartPolicy)

	if err != nil {
		return err
	}

	*o = RestartPolicy(varRestartPolicy)

	return err
}

type NullableRestartPolicy struct {
	value *RestartPolicy
	isSet bool
}

func (v NullableRestartPolicy) Get() *RestartPolicy {
	return v.value
}

func (v *NullableRestartPolicy) Set(val *RestartPolicy) {
	v.value = val
	v.isSet = true
}

func (v NullableRestartPolicy) IsSet() bool {
	return v.isSet
}

func (v *NullableRestartPolicy) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestartPolicy(val *RestartPolicy) *NullableRestartPolicy {
	return &NullableRestartPolicy{value: val, isSet: true}
}

func (v NullableRestartPolicy) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestartPolicy) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


