/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
)

// checks if the StackVolumesData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackVolumesData{}

// StackVolumesData struct for StackVolumesData
type StackVolumesData struct {
	Volumes []Volume `json:"volumes,omitempty"`
}

// NewStackVolumesData instantiates a new StackVolumesData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackVolumesData() *StackVolumesData {
	this := StackVolumesData{}
	return &this
}

// NewStackVolumesDataWithDefaults instantiates a new StackVolumesData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackVolumesDataWithDefaults() *StackVolumesData {
	this := StackVolumesData{}
	return &this
}

// GetVolumes returns the Volumes field value if set, zero value otherwise.
func (o *StackVolumesData) GetVolumes() []Volume {
	if o == nil || IsNil(o.Volumes) {
		var ret []Volume
		return ret
	}
	return o.Volumes
}

// GetVolumesOk returns a tuple with the Volumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StackVolumesData) GetVolumesOk() ([]Volume, bool) {
	if o == nil || IsNil(o.Volumes) {
		return nil, false
	}
	return o.Volumes, true
}

// HasVolumes returns a boolean if a field has been set.
func (o *StackVolumesData) HasVolumes() bool {
	if o != nil && !IsNil(o.Volumes) {
		return true
	}

	return false
}

// SetVolumes gets a reference to the given []Volume and assigns it to the Volumes field.
func (o *StackVolumesData) SetVolumes(v []Volume) {
	o.Volumes = v
}

func (o StackVolumesData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackVolumesData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Volumes) {
		toSerialize["volumes"] = o.Volumes
	}
	return toSerialize, nil
}

type NullableStackVolumesData struct {
	value *StackVolumesData
	isSet bool
}

func (v NullableStackVolumesData) Get() *StackVolumesData {
	return v.value
}

func (v *NullableStackVolumesData) Set(val *StackVolumesData) {
	v.value = val
	v.isSet = true
}

func (v NullableStackVolumesData) IsSet() bool {
	return v.isSet
}

func (v *NullableStackVolumesData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackVolumesData(val *StackVolumesData) *NullableStackVolumesData {
	return &NullableStackVolumesData{value: val, isSet: true}
}

func (v NullableStackVolumesData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackVolumesData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


