/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ScanComparison type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScanComparison{}

// ScanComparison struct for ScanComparison
type ScanComparison struct {
	BaseOnlyImages []string `json:"base_only_images"`
	BaseScan NullableImageScan `json:"base_scan"`
	CommonImages []string `json:"common_images"`
	CompareOnlyImages []string `json:"compare_only_images"`
	CompareScan NullableImageScan `json:"compare_scan"`
	FixedVulnerabilities []ImageVulnerability `json:"fixed_vulnerabilities"`
	NewVulnerabilities []ImageVulnerability `json:"new_vulnerabilities"`
	SameScope bool `json:"same_scope"`
	UnchangedCount int32 `json:"unchanged_count"`
}

type _ScanComparison ScanComparison

// NewScanComparison instantiates a new ScanComparison object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScanComparison(baseOnlyImages []string, baseScan NullableImageScan, commonImages []string, compareOnlyImages []string, compareScan NullableImageScan, fixedVulnerabilities []ImageVulnerability, newVulnerabilities []ImageVulnerability, sameScope bool, unchangedCount int32) *ScanComparison {
	this := ScanComparison{}
	this.BaseOnlyImages = baseOnlyImages
	this.BaseScan = baseScan
	this.CommonImages = commonImages
	this.CompareOnlyImages = compareOnlyImages
	this.CompareScan = compareScan
	this.FixedVulnerabilities = fixedVulnerabilities
	this.NewVulnerabilities = newVulnerabilities
	this.SameScope = sameScope
	this.UnchangedCount = unchangedCount
	return &this
}

// NewScanComparisonWithDefaults instantiates a new ScanComparison object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScanComparisonWithDefaults() *ScanComparison {
	this := ScanComparison{}
	return &this
}

// GetBaseOnlyImages returns the BaseOnlyImages field value
func (o *ScanComparison) GetBaseOnlyImages() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.BaseOnlyImages
}

// GetBaseOnlyImagesOk returns a tuple with the BaseOnlyImages field value
// and a boolean to check if the value has been set.
func (o *ScanComparison) GetBaseOnlyImagesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseOnlyImages, true
}

// SetBaseOnlyImages sets field value
func (o *ScanComparison) SetBaseOnlyImages(v []string) {
	o.BaseOnlyImages = v
}

// GetBaseScan returns the BaseScan field value
// If the value is explicit nil, the zero value for ImageScan will be returned
func (o *ScanComparison) GetBaseScan() ImageScan {
	if o == nil || o.BaseScan.Get() == nil {
		var ret ImageScan
		return ret
	}

	return *o.BaseScan.Get()
}

// GetBaseScanOk returns a tuple with the BaseScan field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScanComparison) GetBaseScanOk() (*ImageScan, bool) {
	if o == nil {
		return nil, false
	}
	return o.BaseScan.Get(), o.BaseScan.IsSet()
}

// SetBaseScan sets field value
func (o *ScanComparison) SetBaseScan(v ImageScan) {
	o.BaseScan.Set(&v)
}

// GetCommonImages returns the CommonImages field value
func (o *ScanComparison) GetCommonImages() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CommonImages
}

// GetCommonImagesOk returns a tuple with the CommonImages field value
// and a boolean to check if the value has been set.
func (o *ScanComparison) GetCommonImagesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CommonImages, true
}

// SetCommonImages sets field value
func (o *ScanComparison) SetCommonImages(v []string) {
	o.CommonImages = v
}

// GetCompareOnlyImages returns the CompareOnlyImages field value
func (o *ScanComparison) GetCompareOnlyImages() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CompareOnlyImages
}

// GetCompareOnlyImagesOk returns a tuple with the CompareOnlyImages field value
// and a boolean to check if the value has been set.
func (o *ScanComparison) GetCompareOnlyImagesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompareOnlyImages, true
}

// SetCompareOnlyImages sets field value
func (o *ScanComparison) SetCompareOnlyImages(v []string) {
	o.CompareOnlyImages = v
}

// GetCompareScan returns the CompareScan field value
// If the value is explicit nil, the zero value for ImageScan will be returned
func (o *ScanComparison) GetCompareScan() ImageScan {
	if o == nil || o.CompareScan.Get() == nil {
		var ret ImageScan
		return ret
	}

	return *o.CompareScan.Get()
}

// GetCompareScanOk returns a tuple with the CompareScan field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScanComparison) GetCompareScanOk() (*ImageScan, bool) {
	if o == nil {
		return nil, false
	}
	return o.CompareScan.Get(), o.CompareScan.IsSet()
}

// SetCompareScan sets field value
func (o *ScanComparison) SetCompareScan(v ImageScan) {
	o.CompareScan.Set(&v)
}

// GetFixedVulnerabilities returns the FixedVulnerabilities field value
func (o *ScanComparison) GetFixedVulnerabilities() []ImageVulnerability {
	if o == nil {
		var ret []ImageVulnerability
		return ret
	}

	return o.FixedVulnerabilities
}

// GetFixedVulnerabilitiesOk returns a tuple with the FixedVulnerabilities field value
// and a boolean to check if the value has been set.
func (o *ScanComparison) GetFixedVulnerabilitiesOk() ([]ImageVulnerability, bool) {
	if o == nil {
		return nil, false
	}
	return o.FixedVulnerabilities, true
}

// SetFixedVulnerabilities sets field value
func (o *ScanComparison) SetFixedVulnerabilities(v []ImageVulnerability) {
	o.FixedVulnerabilities = v
}

// GetNewVulnerabilities returns the NewVulnerabilities field value
func (o *ScanComparison) GetNewVulnerabilities() []ImageVulnerability {
	if o == nil {
		var ret []ImageVulnerability
		return ret
	}

	return o.NewVulnerabilities
}

// GetNewVulnerabilitiesOk returns a tuple with the NewVulnerabilities field value
// and a boolean to check if the value has been set.
func (o *ScanComparison) GetNewVulnerabilitiesOk() ([]ImageVulnerability, bool) {
	if o == nil {
		return nil, false
	}
	return o.NewVulnerabilities, true
}

// SetNewVulnerabilities sets field value
func (o *ScanComparison) SetNewVulnerabilities(v []ImageVulnerability) {
	o.NewVulnerabilities = v
}

// GetSameScope returns the SameScope field value
func (o *ScanComparison) GetSameScope() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SameScope
}

// GetSameScopeOk returns a tuple with the SameScope field value
// and a boolean to check if the value has been set.
func (o *ScanComparison) GetSameScopeOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SameScope, true
}

// SetSameScope sets field value
func (o *ScanComparison) SetSameScope(v bool) {
	o.SameScope = v
}

// GetUnchangedCount returns the UnchangedCount field value
func (o *ScanComparison) GetUnchangedCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UnchangedCount
}

// GetUnchangedCountOk returns a tuple with the UnchangedCount field value
// and a boolean to check if the value has been set.
func (o *ScanComparison) GetUnchangedCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnchangedCount, true
}

// SetUnchangedCount sets field value
func (o *ScanComparison) SetUnchangedCount(v int32) {
	o.UnchangedCount = v
}

func (o ScanComparison) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScanComparison) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["base_only_images"] = o.BaseOnlyImages
	toSerialize["base_scan"] = o.BaseScan.Get()
	toSerialize["common_images"] = o.CommonImages
	toSerialize["compare_only_images"] = o.CompareOnlyImages
	toSerialize["compare_scan"] = o.CompareScan.Get()
	toSerialize["fixed_vulnerabilities"] = o.FixedVulnerabilities
	toSerialize["new_vulnerabilities"] = o.NewVulnerabilities
	toSerialize["same_scope"] = o.SameScope
	toSerialize["unchanged_count"] = o.UnchangedCount
	return toSerialize, nil
}

func (o *ScanComparison) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"base_only_images",
		"base_scan",
		"common_images",
		"compare_only_images",
		"compare_scan",
		"fixed_vulnerabilities",
		"new_vulnerabilities",
		"same_scope",
		"unchanged_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScanComparison := _ScanComparison{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScanComparison)

	if err != nil {
		return err
	}

	*o = ScanComparison(varScanComparison)

	return err
}

type NullableScanComparison struct {
	value *ScanComparison
	isSet bool
}

func (v NullableScanComparison) Get() *ScanComparison {
	return v.value
}

func (v *NullableScanComparison) Set(val *ScanComparison) {
	v.value = val
	v.isSet = true
}

func (v NullableScanComparison) IsSet() bool {
	return v.isSet
}

func (v *NullableScanComparison) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScanComparison(val *ScanComparison) *NullableScanComparison {
	return &NullableScanComparison{value: val, isSet: true}
}

func (v NullableScanComparison) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScanComparison) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


