/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RevokeRoleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RevokeRoleRequest{}

// RevokeRoleRequest struct for RevokeRoleRequest
type RevokeRoleRequest struct {
	RoleId int32 `json:"role_id"`
	UserId int32 `json:"user_id"`
}

type _RevokeRoleRequest RevokeRoleRequest

// NewRevokeRoleRequest instantiates a new RevokeRoleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRevokeRoleRequest(roleId int32, userId int32) *RevokeRoleRequest {
	this := RevokeRoleRequest{}
	this.RoleId = roleId
	this.UserId = userId
	return &this
}

// NewRevokeRoleRequestWithDefaults instantiates a new RevokeRoleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRevokeRoleRequestWithDefaults() *RevokeRoleRequest {
	this := RevokeRoleRequest{}
	return &this
}

// GetRoleId returns the RoleId field value
func (o *RevokeRoleRequest) GetRoleId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.RoleId
}

// GetRoleIdOk returns a tuple with the RoleId field value
// and a boolean to check if the value has been set.
func (o *RevokeRoleRequest) GetRoleIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleId, true
}

// SetRoleId sets field value
func (o *RevokeRoleRequest) SetRoleId(v int32) {
	o.RoleId = v
}

// GetUserId returns the UserId field value
func (o *RevokeRoleRequest) GetUserId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *RevokeRoleRequest) GetUserIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *RevokeRoleRequest) SetUserId(v int32) {
	o.UserId = v
}

func (o RevokeRoleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RevokeRoleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["role_id"] = o.RoleId
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *RevokeRoleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"role_id",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRevokeRoleRequest := _RevokeRoleRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRevokeRoleRequest)

	if err != nil {
		return err
	}

	*o = RevokeRoleRequest(varRevokeRoleRequest)

	return err
}

type NullableRevokeRoleRequest struct {
	value *RevokeRoleRequest
	isSet bool
}

func (v NullableRevokeRoleRequest) Get() *RevokeRoleRequest {
	return v.value
}

func (v *NullableRevokeRoleRequest) Set(val *RevokeRoleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRevokeRoleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRevokeRoleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRevokeRoleRequest(val *RevokeRoleRequest) *NullableRevokeRoleRequest {
	return &NullableRevokeRoleRequest{value: val, isSet: true}
}

func (v NullableRevokeRoleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRevokeRoleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


