/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the ScanTrendPoint type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ScanTrendPoint{}

// ScanTrendPoint struct for ScanTrendPoint
type ScanTrendPoint struct {
	Date time.Time `json:"date"`
	ScanId int32 `json:"scan_id"`
	Summary NullableVulnerabilitySummary `json:"summary"`
}

type _ScanTrendPoint ScanTrendPoint

// NewScanTrendPoint instantiates a new ScanTrendPoint object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScanTrendPoint(date time.Time, scanId int32, summary NullableVulnerabilitySummary) *ScanTrendPoint {
	this := ScanTrendPoint{}
	this.Date = date
	this.ScanId = scanId
	this.Summary = summary
	return &this
}

// NewScanTrendPointWithDefaults instantiates a new ScanTrendPoint object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScanTrendPointWithDefaults() *ScanTrendPoint {
	this := ScanTrendPoint{}
	return &this
}

// GetDate returns the Date field value
func (o *ScanTrendPoint) GetDate() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *ScanTrendPoint) GetDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *ScanTrendPoint) SetDate(v time.Time) {
	o.Date = v
}

// GetScanId returns the ScanId field value
func (o *ScanTrendPoint) GetScanId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ScanId
}

// GetScanIdOk returns a tuple with the ScanId field value
// and a boolean to check if the value has been set.
func (o *ScanTrendPoint) GetScanIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ScanId, true
}

// SetScanId sets field value
func (o *ScanTrendPoint) SetScanId(v int32) {
	o.ScanId = v
}

// GetSummary returns the Summary field value
// If the value is explicit nil, the zero value for VulnerabilitySummary will be returned
func (o *ScanTrendPoint) GetSummary() VulnerabilitySummary {
	if o == nil || o.Summary.Get() == nil {
		var ret VulnerabilitySummary
		return ret
	}

	return *o.Summary.Get()
}

// GetSummaryOk returns a tuple with the Summary field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ScanTrendPoint) GetSummaryOk() (*VulnerabilitySummary, bool) {
	if o == nil {
		return nil, false
	}
	return o.Summary.Get(), o.Summary.IsSet()
}

// SetSummary sets field value
func (o *ScanTrendPoint) SetSummary(v VulnerabilitySummary) {
	o.Summary.Set(&v)
}

func (o ScanTrendPoint) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ScanTrendPoint) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["date"] = o.Date
	toSerialize["scan_id"] = o.ScanId
	toSerialize["summary"] = o.Summary.Get()
	return toSerialize, nil
}

func (o *ScanTrendPoint) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"date",
		"scan_id",
		"summary",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varScanTrendPoint := _ScanTrendPoint{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varScanTrendPoint)

	if err != nil {
		return err
	}

	*o = ScanTrendPoint(varScanTrendPoint)

	return err
}

type NullableScanTrendPoint struct {
	value *ScanTrendPoint
	isSet bool
}

func (v NullableScanTrendPoint) Get() *ScanTrendPoint {
	return v.value
}

func (v *NullableScanTrendPoint) Set(val *ScanTrendPoint) {
	v.value = val
	v.isSet = true
}

func (v NullableScanTrendPoint) IsSet() bool {
	return v.isSet
}

func (v *NullableScanTrendPoint) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScanTrendPoint(val *ScanTrendPoint) *NullableScanTrendPoint {
	return &NullableScanTrendPoint{value: val, isSet: true}
}

func (v NullableScanTrendPoint) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScanTrendPoint) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


