/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StackHealthDetails type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackHealthDetails{}

// StackHealthDetails struct for StackHealthDetails
type StackHealthDetails struct {
	HealthyCount int32 `json:"healthy_count"`
	Percentage int32 `json:"percentage"`
	Reasons []string `json:"reasons"`
	StoppedCount int32 `json:"stopped_count"`
	UnhealthyCount int32 `json:"unhealthy_count"`
}

type _StackHealthDetails StackHealthDetails

// NewStackHealthDetails instantiates a new StackHealthDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackHealthDetails(healthyCount int32, percentage int32, reasons []string, stoppedCount int32, unhealthyCount int32) *StackHealthDetails {
	this := StackHealthDetails{}
	this.HealthyCount = healthyCount
	this.Percentage = percentage
	this.Reasons = reasons
	this.StoppedCount = stoppedCount
	this.UnhealthyCount = unhealthyCount
	return &this
}

// NewStackHealthDetailsWithDefaults instantiates a new StackHealthDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackHealthDetailsWithDefaults() *StackHealthDetails {
	this := StackHealthDetails{}
	return &this
}

// GetHealthyCount returns the HealthyCount field value
func (o *StackHealthDetails) GetHealthyCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.HealthyCount
}

// GetHealthyCountOk returns a tuple with the HealthyCount field value
// and a boolean to check if the value has been set.
func (o *StackHealthDetails) GetHealthyCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HealthyCount, true
}

// SetHealthyCount sets field value
func (o *StackHealthDetails) SetHealthyCount(v int32) {
	o.HealthyCount = v
}

// GetPercentage returns the Percentage field value
func (o *StackHealthDetails) GetPercentage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Percentage
}

// GetPercentageOk returns a tuple with the Percentage field value
// and a boolean to check if the value has been set.
func (o *StackHealthDetails) GetPercentageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Percentage, true
}

// SetPercentage sets field value
func (o *StackHealthDetails) SetPercentage(v int32) {
	o.Percentage = v
}

// GetReasons returns the Reasons field value
func (o *StackHealthDetails) GetReasons() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Reasons
}

// GetReasonsOk returns a tuple with the Reasons field value
// and a boolean to check if the value has been set.
func (o *StackHealthDetails) GetReasonsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reasons, true
}

// SetReasons sets field value
func (o *StackHealthDetails) SetReasons(v []string) {
	o.Reasons = v
}

// GetStoppedCount returns the StoppedCount field value
func (o *StackHealthDetails) GetStoppedCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.StoppedCount
}

// GetStoppedCountOk returns a tuple with the StoppedCount field value
// and a boolean to check if the value has been set.
func (o *StackHealthDetails) GetStoppedCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StoppedCount, true
}

// SetStoppedCount sets field value
func (o *StackHealthDetails) SetStoppedCount(v int32) {
	o.StoppedCount = v
}

// GetUnhealthyCount returns the UnhealthyCount field value
func (o *StackHealthDetails) GetUnhealthyCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UnhealthyCount
}

// GetUnhealthyCountOk returns a tuple with the UnhealthyCount field value
// and a boolean to check if the value has been set.
func (o *StackHealthDetails) GetUnhealthyCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UnhealthyCount, true
}

// SetUnhealthyCount sets field value
func (o *StackHealthDetails) SetUnhealthyCount(v int32) {
	o.UnhealthyCount = v
}

func (o StackHealthDetails) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackHealthDetails) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["healthy_count"] = o.HealthyCount
	toSerialize["percentage"] = o.Percentage
	toSerialize["reasons"] = o.Reasons
	toSerialize["stopped_count"] = o.StoppedCount
	toSerialize["unhealthy_count"] = o.UnhealthyCount
	return toSerialize, nil
}

func (o *StackHealthDetails) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"healthy_count",
		"percentage",
		"reasons",
		"stopped_count",
		"unhealthy_count",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStackHealthDetails := _StackHealthDetails{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStackHealthDetails)

	if err != nil {
		return err
	}

	*o = StackHealthDetails(varStackHealthDetails)

	return err
}

type NullableStackHealthDetails struct {
	value *StackHealthDetails
	isSet bool
}

func (v NullableStackHealthDetails) Get() *StackHealthDetails {
	return v.value
}

func (v *NullableStackHealthDetails) Set(val *StackHealthDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableStackHealthDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableStackHealthDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackHealthDetails(val *StackHealthDetails) *NullableStackHealthDetails {
	return &NullableStackHealthDetails{value: val, isSet: true}
}

func (v NullableStackHealthDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackHealthDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


