/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListRolesData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListRolesData{}

// ListRolesData struct for ListRolesData
type ListRolesData struct {
	Roles []RoleWithPermissions `json:"roles"`
}

type _ListRolesData ListRolesData

// NewListRolesData instantiates a new ListRolesData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListRolesData(roles []RoleWithPermissions) *ListRolesData {
	this := ListRolesData{}
	this.Roles = roles
	return &this
}

// NewListRolesDataWithDefaults instantiates a new ListRolesData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListRolesDataWithDefaults() *ListRolesData {
	this := ListRolesData{}
	return &this
}

// GetRoles returns the Roles field value
func (o *ListRolesData) GetRoles() []RoleWithPermissions {
	if o == nil {
		var ret []RoleWithPermissions
		return ret
	}

	return o.Roles
}

// GetRolesOk returns a tuple with the Roles field value
// and a boolean to check if the value has been set.
func (o *ListRolesData) GetRolesOk() ([]RoleWithPermissions, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roles, true
}

// SetRoles sets field value
func (o *ListRolesData) SetRoles(v []RoleWithPermissions) {
	o.Roles = v
}

func (o ListRolesData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListRolesData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roles"] = o.Roles
	return toSerialize, nil
}

func (o *ListRolesData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListRolesData := _ListRolesData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListRolesData)

	if err != nil {
		return err
	}

	*o = ListRolesData(varListRolesData)

	return err
}

type NullableListRolesData struct {
	value *ListRolesData
	isSet bool
}

func (v NullableListRolesData) Get() *ListRolesData {
	return v.value
}

func (v *NullableListRolesData) Set(val *ListRolesData) {
	v.value = val
	v.isSet = true
}

func (v NullableListRolesData) IsSet() bool {
	return v.isSet
}

func (v *NullableListRolesData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListRolesData(val *ListRolesData) *NullableListRolesData {
	return &NullableListRolesData{value: val, isSet: true}
}

func (v NullableListRolesData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListRolesData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


