/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdminListServersData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminListServersData{}

// AdminListServersData struct for AdminListServersData
type AdminListServersData struct {
	Servers []ServerInfo `json:"servers"`
}

type _AdminListServersData AdminListServersData

// NewAdminListServersData instantiates a new AdminListServersData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminListServersData(servers []ServerInfo) *AdminListServersData {
	this := AdminListServersData{}
	this.Servers = servers
	return &this
}

// NewAdminListServersDataWithDefaults instantiates a new AdminListServersData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminListServersDataWithDefaults() *AdminListServersData {
	this := AdminListServersData{}
	return &this
}

// GetServers returns the Servers field value
func (o *AdminListServersData) GetServers() []ServerInfo {
	if o == nil {
		var ret []ServerInfo
		return ret
	}

	return o.Servers
}

// GetServersOk returns a tuple with the Servers field value
// and a boolean to check if the value has been set.
func (o *AdminListServersData) GetServersOk() ([]ServerInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Servers, true
}

// SetServers sets field value
func (o *AdminListServersData) SetServers(v []ServerInfo) {
	o.Servers = v
}

func (o AdminListServersData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminListServersData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["servers"] = o.Servers
	return toSerialize, nil
}

func (o *AdminListServersData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"servers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminListServersData := _AdminListServersData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdminListServersData)

	if err != nil {
		return err
	}

	*o = AdminListServersData(varAdminListServersData)

	return err
}

type NullableAdminListServersData struct {
	value *AdminListServersData
	isSet bool
}

func (v NullableAdminListServersData) Get() *AdminListServersData {
	return v.value
}

func (v *NullableAdminListServersData) Set(val *AdminListServersData) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminListServersData) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminListServersData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminListServersData(val *AdminListServersData) *NullableAdminListServersData {
	return &NullableAdminListServersData{value: val, isSet: true}
}

func (v NullableAdminListServersData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminListServersData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


