/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DirectoryListing type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DirectoryListing{}

// DirectoryListing struct for DirectoryListing
type DirectoryListing struct {
	Entries []FileEntry `json:"entries"`
	Path string `json:"path"`
}

type _DirectoryListing DirectoryListing

// NewDirectoryListing instantiates a new DirectoryListing object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectoryListing(entries []FileEntry, path string) *DirectoryListing {
	this := DirectoryListing{}
	this.Entries = entries
	this.Path = path
	return &this
}

// NewDirectoryListingWithDefaults instantiates a new DirectoryListing object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryListingWithDefaults() *DirectoryListing {
	this := DirectoryListing{}
	return &this
}

// GetEntries returns the Entries field value
func (o *DirectoryListing) GetEntries() []FileEntry {
	if o == nil {
		var ret []FileEntry
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *DirectoryListing) GetEntriesOk() ([]FileEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *DirectoryListing) SetEntries(v []FileEntry) {
	o.Entries = v
}

// GetPath returns the Path field value
func (o *DirectoryListing) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *DirectoryListing) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *DirectoryListing) SetPath(v string) {
	o.Path = v
}

func (o DirectoryListing) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DirectoryListing) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["entries"] = o.Entries
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

func (o *DirectoryListing) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"entries",
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectoryListing := _DirectoryListing{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDirectoryListing)

	if err != nil {
		return err
	}

	*o = DirectoryListing(varDirectoryListing)

	return err
}

type NullableDirectoryListing struct {
	value *DirectoryListing
	isSet bool
}

func (v NullableDirectoryListing) Get() *DirectoryListing {
	return v.value
}

func (v *NullableDirectoryListing) Set(val *DirectoryListing) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectoryListing) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectoryListing) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectoryListing(val *DirectoryListing) *NullableDirectoryListing {
	return &NullableDirectoryListing{value: val, isSet: true}
}

func (v NullableDirectoryListing) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectoryListing) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


