/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
)

// checks if the ServiceNetworkConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceNetworkConfig{}

// ServiceNetworkConfig struct for ServiceNetworkConfig
type ServiceNetworkConfig struct {
	Aliases []string `json:"aliases,omitempty"`
	Ipv4Address *string `json:"ipv4_address,omitempty"`
	Ipv6Address *string `json:"ipv6_address,omitempty"`
	Priority *int32 `json:"priority,omitempty"`
}

// NewServiceNetworkConfig instantiates a new ServiceNetworkConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceNetworkConfig() *ServiceNetworkConfig {
	this := ServiceNetworkConfig{}
	return &this
}

// NewServiceNetworkConfigWithDefaults instantiates a new ServiceNetworkConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceNetworkConfigWithDefaults() *ServiceNetworkConfig {
	this := ServiceNetworkConfig{}
	return &this
}

// GetAliases returns the Aliases field value if set, zero value otherwise.
func (o *ServiceNetworkConfig) GetAliases() []string {
	if o == nil || IsNil(o.Aliases) {
		var ret []string
		return ret
	}
	return o.Aliases
}

// GetAliasesOk returns a tuple with the Aliases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceNetworkConfig) GetAliasesOk() ([]string, bool) {
	if o == nil || IsNil(o.Aliases) {
		return nil, false
	}
	return o.Aliases, true
}

// HasAliases returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasAliases() bool {
	if o != nil && !IsNil(o.Aliases) {
		return true
	}

	return false
}

// SetAliases gets a reference to the given []string and assigns it to the Aliases field.
func (o *ServiceNetworkConfig) SetAliases(v []string) {
	o.Aliases = v
}

// GetIpv4Address returns the Ipv4Address field value if set, zero value otherwise.
func (o *ServiceNetworkConfig) GetIpv4Address() string {
	if o == nil || IsNil(o.Ipv4Address) {
		var ret string
		return ret
	}
	return *o.Ipv4Address
}

// GetIpv4AddressOk returns a tuple with the Ipv4Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceNetworkConfig) GetIpv4AddressOk() (*string, bool) {
	if o == nil || IsNil(o.Ipv4Address) {
		return nil, false
	}
	return o.Ipv4Address, true
}

// HasIpv4Address returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasIpv4Address() bool {
	if o != nil && !IsNil(o.Ipv4Address) {
		return true
	}

	return false
}

// SetIpv4Address gets a reference to the given string and assigns it to the Ipv4Address field.
func (o *ServiceNetworkConfig) SetIpv4Address(v string) {
	o.Ipv4Address = &v
}

// GetIpv6Address returns the Ipv6Address field value if set, zero value otherwise.
func (o *ServiceNetworkConfig) GetIpv6Address() string {
	if o == nil || IsNil(o.Ipv6Address) {
		var ret string
		return ret
	}
	return *o.Ipv6Address
}

// GetIpv6AddressOk returns a tuple with the Ipv6Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceNetworkConfig) GetIpv6AddressOk() (*string, bool) {
	if o == nil || IsNil(o.Ipv6Address) {
		return nil, false
	}
	return o.Ipv6Address, true
}

// HasIpv6Address returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasIpv6Address() bool {
	if o != nil && !IsNil(o.Ipv6Address) {
		return true
	}

	return false
}

// SetIpv6Address gets a reference to the given string and assigns it to the Ipv6Address field.
func (o *ServiceNetworkConfig) SetIpv6Address(v string) {
	o.Ipv6Address = &v
}

// GetPriority returns the Priority field value if set, zero value otherwise.
func (o *ServiceNetworkConfig) GetPriority() int32 {
	if o == nil || IsNil(o.Priority) {
		var ret int32
		return ret
	}
	return *o.Priority
}

// GetPriorityOk returns a tuple with the Priority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceNetworkConfig) GetPriorityOk() (*int32, bool) {
	if o == nil || IsNil(o.Priority) {
		return nil, false
	}
	return o.Priority, true
}

// HasPriority returns a boolean if a field has been set.
func (o *ServiceNetworkConfig) HasPriority() bool {
	if o != nil && !IsNil(o.Priority) {
		return true
	}

	return false
}

// SetPriority gets a reference to the given int32 and assigns it to the Priority field.
func (o *ServiceNetworkConfig) SetPriority(v int32) {
	o.Priority = &v
}

func (o ServiceNetworkConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceNetworkConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Aliases) {
		toSerialize["aliases"] = o.Aliases
	}
	if !IsNil(o.Ipv4Address) {
		toSerialize["ipv4_address"] = o.Ipv4Address
	}
	if !IsNil(o.Ipv6Address) {
		toSerialize["ipv6_address"] = o.Ipv6Address
	}
	if !IsNil(o.Priority) {
		toSerialize["priority"] = o.Priority
	}
	return toSerialize, nil
}

type NullableServiceNetworkConfig struct {
	value *ServiceNetworkConfig
	isSet bool
}

func (v NullableServiceNetworkConfig) Get() *ServiceNetworkConfig {
	return v.value
}

func (v *NullableServiceNetworkConfig) Set(val *ServiceNetworkConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceNetworkConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceNetworkConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceNetworkConfig(val *ServiceNetworkConfig) *NullableServiceNetworkConfig {
	return &NullableServiceNetworkConfig{value: val, isSet: true}
}

func (v NullableServiceNetworkConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceNetworkConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


