/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VersionData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VersionData{}

// VersionData struct for VersionData
type VersionData struct {
	Version string `json:"version"`
}

type _VersionData VersionData

// NewVersionData instantiates a new VersionData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVersionData(version string) *VersionData {
	this := VersionData{}
	this.Version = version
	return &this
}

// NewVersionDataWithDefaults instantiates a new VersionData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVersionDataWithDefaults() *VersionData {
	this := VersionData{}
	return &this
}

// GetVersion returns the Version field value
func (o *VersionData) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *VersionData) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *VersionData) SetVersion(v string) {
	o.Version = v
}

func (o VersionData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VersionData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	return toSerialize, nil
}

func (o *VersionData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVersionData := _VersionData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVersionData)

	if err != nil {
		return err
	}

	*o = VersionData(varVersionData)

	return err
}

type NullableVersionData struct {
	value *VersionData
	isSet bool
}

func (v NullableVersionData) Get() *VersionData {
	return v.value
}

func (v *NullableVersionData) Set(val *VersionData) {
	v.value = val
	v.isSet = true
}

func (v NullableVersionData) IsSet() bool {
	return v.isSet
}

func (v *NullableVersionData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVersionData(val *VersionData) *NullableVersionData {
	return &NullableVersionData{value: val, isSet: true}
}

func (v NullableVersionData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVersionData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


