/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
)

// checks if the NetworkConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NetworkConfig{}

// NetworkConfig struct for NetworkConfig
type NetworkConfig struct {
	Driver *string `json:"driver,omitempty"`
	DriverOpts *map[string]string `json:"driver_opts,omitempty"`
	External *bool `json:"external,omitempty"`
	Ipam NullableIpamConfig `json:"ipam,omitempty"`
	Labels *map[string]string `json:"labels,omitempty"`
	Name *string `json:"name,omitempty"`
}

// NewNetworkConfig instantiates a new NetworkConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNetworkConfig() *NetworkConfig {
	this := NetworkConfig{}
	return &this
}

// NewNetworkConfigWithDefaults instantiates a new NetworkConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNetworkConfigWithDefaults() *NetworkConfig {
	this := NetworkConfig{}
	return &this
}

// GetDriver returns the Driver field value if set, zero value otherwise.
func (o *NetworkConfig) GetDriver() string {
	if o == nil || IsNil(o.Driver) {
		var ret string
		return ret
	}
	return *o.Driver
}

// GetDriverOk returns a tuple with the Driver field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkConfig) GetDriverOk() (*string, bool) {
	if o == nil || IsNil(o.Driver) {
		return nil, false
	}
	return o.Driver, true
}

// HasDriver returns a boolean if a field has been set.
func (o *NetworkConfig) HasDriver() bool {
	if o != nil && !IsNil(o.Driver) {
		return true
	}

	return false
}

// SetDriver gets a reference to the given string and assigns it to the Driver field.
func (o *NetworkConfig) SetDriver(v string) {
	o.Driver = &v
}

// GetDriverOpts returns the DriverOpts field value if set, zero value otherwise.
func (o *NetworkConfig) GetDriverOpts() map[string]string {
	if o == nil || IsNil(o.DriverOpts) {
		var ret map[string]string
		return ret
	}
	return *o.DriverOpts
}

// GetDriverOptsOk returns a tuple with the DriverOpts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkConfig) GetDriverOptsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.DriverOpts) {
		return nil, false
	}
	return o.DriverOpts, true
}

// HasDriverOpts returns a boolean if a field has been set.
func (o *NetworkConfig) HasDriverOpts() bool {
	if o != nil && !IsNil(o.DriverOpts) {
		return true
	}

	return false
}

// SetDriverOpts gets a reference to the given map[string]string and assigns it to the DriverOpts field.
func (o *NetworkConfig) SetDriverOpts(v map[string]string) {
	o.DriverOpts = &v
}

// GetExternal returns the External field value if set, zero value otherwise.
func (o *NetworkConfig) GetExternal() bool {
	if o == nil || IsNil(o.External) {
		var ret bool
		return ret
	}
	return *o.External
}

// GetExternalOk returns a tuple with the External field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkConfig) GetExternalOk() (*bool, bool) {
	if o == nil || IsNil(o.External) {
		return nil, false
	}
	return o.External, true
}

// HasExternal returns a boolean if a field has been set.
func (o *NetworkConfig) HasExternal() bool {
	if o != nil && !IsNil(o.External) {
		return true
	}

	return false
}

// SetExternal gets a reference to the given bool and assigns it to the External field.
func (o *NetworkConfig) SetExternal(v bool) {
	o.External = &v
}

// GetIpam returns the Ipam field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *NetworkConfig) GetIpam() IpamConfig {
	if o == nil || IsNil(o.Ipam.Get()) {
		var ret IpamConfig
		return ret
	}
	return *o.Ipam.Get()
}

// GetIpamOk returns a tuple with the Ipam field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *NetworkConfig) GetIpamOk() (*IpamConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ipam.Get(), o.Ipam.IsSet()
}

// HasIpam returns a boolean if a field has been set.
func (o *NetworkConfig) HasIpam() bool {
	if o != nil && o.Ipam.IsSet() {
		return true
	}

	return false
}

// SetIpam gets a reference to the given NullableIpamConfig and assigns it to the Ipam field.
func (o *NetworkConfig) SetIpam(v IpamConfig) {
	o.Ipam.Set(&v)
}
// SetIpamNil sets the value for Ipam to be an explicit nil
func (o *NetworkConfig) SetIpamNil() {
	o.Ipam.Set(nil)
}

// UnsetIpam ensures that no value is present for Ipam, not even an explicit nil
func (o *NetworkConfig) UnsetIpam() {
	o.Ipam.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *NetworkConfig) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkConfig) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *NetworkConfig) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *NetworkConfig) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *NetworkConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NetworkConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *NetworkConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *NetworkConfig) SetName(v string) {
	o.Name = &v
}

func (o NetworkConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NetworkConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Driver) {
		toSerialize["driver"] = o.Driver
	}
	if !IsNil(o.DriverOpts) {
		toSerialize["driver_opts"] = o.DriverOpts
	}
	if !IsNil(o.External) {
		toSerialize["external"] = o.External
	}
	if o.Ipam.IsSet() {
		toSerialize["ipam"] = o.Ipam.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableNetworkConfig struct {
	value *NetworkConfig
	isSet bool
}

func (v NullableNetworkConfig) Get() *NetworkConfig {
	return v.value
}

func (v *NullableNetworkConfig) Set(val *NetworkConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableNetworkConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableNetworkConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNetworkConfig(val *NetworkConfig) *NullableNetworkConfig {
	return &NullableNetworkConfig{value: val, isSet: true}
}

func (v NullableNetworkConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNetworkConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


