/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the NewServiceConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NewServiceConfig{}

// NewServiceConfig struct for NewServiceConfig
type NewServiceConfig struct {
	Environment *map[string]string `json:"environment,omitempty"`
	Image string `json:"image"`
	Ports []PortMapping `json:"ports,omitempty"`
	Restart *string `json:"restart,omitempty"`
	Volumes []VolumeMount2 `json:"volumes,omitempty"`
}

type _NewServiceConfig NewServiceConfig

// NewNewServiceConfig instantiates a new NewServiceConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNewServiceConfig(image string) *NewServiceConfig {
	this := NewServiceConfig{}
	this.Image = image
	return &this
}

// NewNewServiceConfigWithDefaults instantiates a new NewServiceConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNewServiceConfigWithDefaults() *NewServiceConfig {
	this := NewServiceConfig{}
	return &this
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *NewServiceConfig) GetEnvironment() map[string]string {
	if o == nil || IsNil(o.Environment) {
		var ret map[string]string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewServiceConfig) GetEnvironmentOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *NewServiceConfig) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given map[string]string and assigns it to the Environment field.
func (o *NewServiceConfig) SetEnvironment(v map[string]string) {
	o.Environment = &v
}

// GetImage returns the Image field value
func (o *NewServiceConfig) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *NewServiceConfig) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *NewServiceConfig) SetImage(v string) {
	o.Image = v
}

// GetPorts returns the Ports field value if set, zero value otherwise.
func (o *NewServiceConfig) GetPorts() []PortMapping {
	if o == nil || IsNil(o.Ports) {
		var ret []PortMapping
		return ret
	}
	return o.Ports
}

// GetPortsOk returns a tuple with the Ports field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewServiceConfig) GetPortsOk() ([]PortMapping, bool) {
	if o == nil || IsNil(o.Ports) {
		return nil, false
	}
	return o.Ports, true
}

// HasPorts returns a boolean if a field has been set.
func (o *NewServiceConfig) HasPorts() bool {
	if o != nil && !IsNil(o.Ports) {
		return true
	}

	return false
}

// SetPorts gets a reference to the given []PortMapping and assigns it to the Ports field.
func (o *NewServiceConfig) SetPorts(v []PortMapping) {
	o.Ports = v
}

// GetRestart returns the Restart field value if set, zero value otherwise.
func (o *NewServiceConfig) GetRestart() string {
	if o == nil || IsNil(o.Restart) {
		var ret string
		return ret
	}
	return *o.Restart
}

// GetRestartOk returns a tuple with the Restart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewServiceConfig) GetRestartOk() (*string, bool) {
	if o == nil || IsNil(o.Restart) {
		return nil, false
	}
	return o.Restart, true
}

// HasRestart returns a boolean if a field has been set.
func (o *NewServiceConfig) HasRestart() bool {
	if o != nil && !IsNil(o.Restart) {
		return true
	}

	return false
}

// SetRestart gets a reference to the given string and assigns it to the Restart field.
func (o *NewServiceConfig) SetRestart(v string) {
	o.Restart = &v
}

// GetVolumes returns the Volumes field value if set, zero value otherwise.
func (o *NewServiceConfig) GetVolumes() []VolumeMount2 {
	if o == nil || IsNil(o.Volumes) {
		var ret []VolumeMount2
		return ret
	}
	return o.Volumes
}

// GetVolumesOk returns a tuple with the Volumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NewServiceConfig) GetVolumesOk() ([]VolumeMount2, bool) {
	if o == nil || IsNil(o.Volumes) {
		return nil, false
	}
	return o.Volumes, true
}

// HasVolumes returns a boolean if a field has been set.
func (o *NewServiceConfig) HasVolumes() bool {
	if o != nil && !IsNil(o.Volumes) {
		return true
	}

	return false
}

// SetVolumes gets a reference to the given []VolumeMount2 and assigns it to the Volumes field.
func (o *NewServiceConfig) SetVolumes(v []VolumeMount2) {
	o.Volumes = v
}

func (o NewServiceConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NewServiceConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	toSerialize["image"] = o.Image
	if !IsNil(o.Ports) {
		toSerialize["ports"] = o.Ports
	}
	if !IsNil(o.Restart) {
		toSerialize["restart"] = o.Restart
	}
	if !IsNil(o.Volumes) {
		toSerialize["volumes"] = o.Volumes
	}
	return toSerialize, nil
}

func (o *NewServiceConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"image",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNewServiceConfig := _NewServiceConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNewServiceConfig)

	if err != nil {
		return err
	}

	*o = NewServiceConfig(varNewServiceConfig)

	return err
}

type NullableNewServiceConfig struct {
	value *NewServiceConfig
	isSet bool
}

func (v NullableNewServiceConfig) Get() *NewServiceConfig {
	return v.value
}

func (v *NullableNewServiceConfig) Set(val *NewServiceConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableNewServiceConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableNewServiceConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNewServiceConfig(val *NewServiceConfig) *NullableNewServiceConfig {
	return &NullableNewServiceConfig{value: val, isSet: true}
}

func (v NullableNewServiceConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNewServiceConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


