/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RootFS type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RootFS{}

// RootFS struct for RootFS
type RootFS struct {
	Layers []string `json:"layers,omitempty"`
	Type string `json:"type"`
}

type _RootFS RootFS

// NewRootFS instantiates a new RootFS object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRootFS(type_ string) *RootFS {
	this := RootFS{}
	this.Type = type_
	return &this
}

// NewRootFSWithDefaults instantiates a new RootFS object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRootFSWithDefaults() *RootFS {
	this := RootFS{}
	return &this
}

// GetLayers returns the Layers field value if set, zero value otherwise.
func (o *RootFS) GetLayers() []string {
	if o == nil || IsNil(o.Layers) {
		var ret []string
		return ret
	}
	return o.Layers
}

// GetLayersOk returns a tuple with the Layers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RootFS) GetLayersOk() ([]string, bool) {
	if o == nil || IsNil(o.Layers) {
		return nil, false
	}
	return o.Layers, true
}

// HasLayers returns a boolean if a field has been set.
func (o *RootFS) HasLayers() bool {
	if o != nil && !IsNil(o.Layers) {
		return true
	}

	return false
}

// SetLayers gets a reference to the given []string and assigns it to the Layers field.
func (o *RootFS) SetLayers(v []string) {
	o.Layers = v
}

// GetType returns the Type field value
func (o *RootFS) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *RootFS) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *RootFS) SetType(v string) {
	o.Type = v
}

func (o RootFS) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RootFS) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Layers) {
		toSerialize["layers"] = o.Layers
	}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *RootFS) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRootFS := _RootFS{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRootFS)

	if err != nil {
		return err
	}

	*o = RootFS(varRootFS)

	return err
}

type NullableRootFS struct {
	value *RootFS
	isSet bool
}

func (v NullableRootFS) Get() *RootFS {
	return v.value
}

func (v *NullableRootFS) Set(val *RootFS) {
	v.value = val
	v.isSet = true
}

func (v NullableRootFS) IsSet() bool {
	return v.isSet
}

func (v *NullableRootFS) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRootFS(val *RootFS) *NullableRootFS {
	return &NullableRootFS{value: val, isSet: true}
}

func (v NullableRootFS) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRootFS) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


