/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
)

// checks if the ServiceChanges type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceChanges{}

// ServiceChanges struct for ServiceChanges
type ServiceChanges struct {
	Build NullableBuildConfig `json:"build,omitempty"`
	Command NullableCommandConfig `json:"command,omitempty"`
	DependsOn *map[string]DependsOnConfig `json:"depends_on,omitempty"`
	Deploy NullableDeployConfig `json:"deploy,omitempty"`
	Entrypoint NullableCommandConfig `json:"entrypoint,omitempty"`
	Environment *map[string]string `json:"environment,omitempty"`
	Healthcheck NullableHealthcheckConfig `json:"healthcheck,omitempty"`
	Image NullableString `json:"image,omitempty"`
	Labels *map[string]string `json:"labels,omitempty"`
	Networks map[string]ServiceNetworkConfig `json:"networks,omitempty"`
	Ports []PortMapping `json:"ports,omitempty"`
	Restart NullableString `json:"restart,omitempty"`
	Volumes []VolumeMount2 `json:"volumes,omitempty"`
}

// NewServiceChanges instantiates a new ServiceChanges object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceChanges() *ServiceChanges {
	this := ServiceChanges{}
	return &this
}

// NewServiceChangesWithDefaults instantiates a new ServiceChanges object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceChangesWithDefaults() *ServiceChanges {
	this := ServiceChanges{}
	return &this
}

// GetBuild returns the Build field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceChanges) GetBuild() BuildConfig {
	if o == nil || IsNil(o.Build.Get()) {
		var ret BuildConfig
		return ret
	}
	return *o.Build.Get()
}

// GetBuildOk returns a tuple with the Build field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceChanges) GetBuildOk() (*BuildConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Build.Get(), o.Build.IsSet()
}

// HasBuild returns a boolean if a field has been set.
func (o *ServiceChanges) HasBuild() bool {
	if o != nil && o.Build.IsSet() {
		return true
	}

	return false
}

// SetBuild gets a reference to the given NullableBuildConfig and assigns it to the Build field.
func (o *ServiceChanges) SetBuild(v BuildConfig) {
	o.Build.Set(&v)
}
// SetBuildNil sets the value for Build to be an explicit nil
func (o *ServiceChanges) SetBuildNil() {
	o.Build.Set(nil)
}

// UnsetBuild ensures that no value is present for Build, not even an explicit nil
func (o *ServiceChanges) UnsetBuild() {
	o.Build.Unset()
}

// GetCommand returns the Command field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceChanges) GetCommand() CommandConfig {
	if o == nil || IsNil(o.Command.Get()) {
		var ret CommandConfig
		return ret
	}
	return *o.Command.Get()
}

// GetCommandOk returns a tuple with the Command field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceChanges) GetCommandOk() (*CommandConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Command.Get(), o.Command.IsSet()
}

// HasCommand returns a boolean if a field has been set.
func (o *ServiceChanges) HasCommand() bool {
	if o != nil && o.Command.IsSet() {
		return true
	}

	return false
}

// SetCommand gets a reference to the given NullableCommandConfig and assigns it to the Command field.
func (o *ServiceChanges) SetCommand(v CommandConfig) {
	o.Command.Set(&v)
}
// SetCommandNil sets the value for Command to be an explicit nil
func (o *ServiceChanges) SetCommandNil() {
	o.Command.Set(nil)
}

// UnsetCommand ensures that no value is present for Command, not even an explicit nil
func (o *ServiceChanges) UnsetCommand() {
	o.Command.Unset()
}

// GetDependsOn returns the DependsOn field value if set, zero value otherwise.
func (o *ServiceChanges) GetDependsOn() map[string]DependsOnConfig {
	if o == nil || IsNil(o.DependsOn) {
		var ret map[string]DependsOnConfig
		return ret
	}
	return *o.DependsOn
}

// GetDependsOnOk returns a tuple with the DependsOn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceChanges) GetDependsOnOk() (*map[string]DependsOnConfig, bool) {
	if o == nil || IsNil(o.DependsOn) {
		return nil, false
	}
	return o.DependsOn, true
}

// HasDependsOn returns a boolean if a field has been set.
func (o *ServiceChanges) HasDependsOn() bool {
	if o != nil && !IsNil(o.DependsOn) {
		return true
	}

	return false
}

// SetDependsOn gets a reference to the given map[string]DependsOnConfig and assigns it to the DependsOn field.
func (o *ServiceChanges) SetDependsOn(v map[string]DependsOnConfig) {
	o.DependsOn = &v
}

// GetDeploy returns the Deploy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceChanges) GetDeploy() DeployConfig {
	if o == nil || IsNil(o.Deploy.Get()) {
		var ret DeployConfig
		return ret
	}
	return *o.Deploy.Get()
}

// GetDeployOk returns a tuple with the Deploy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceChanges) GetDeployOk() (*DeployConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Deploy.Get(), o.Deploy.IsSet()
}

// HasDeploy returns a boolean if a field has been set.
func (o *ServiceChanges) HasDeploy() bool {
	if o != nil && o.Deploy.IsSet() {
		return true
	}

	return false
}

// SetDeploy gets a reference to the given NullableDeployConfig and assigns it to the Deploy field.
func (o *ServiceChanges) SetDeploy(v DeployConfig) {
	o.Deploy.Set(&v)
}
// SetDeployNil sets the value for Deploy to be an explicit nil
func (o *ServiceChanges) SetDeployNil() {
	o.Deploy.Set(nil)
}

// UnsetDeploy ensures that no value is present for Deploy, not even an explicit nil
func (o *ServiceChanges) UnsetDeploy() {
	o.Deploy.Unset()
}

// GetEntrypoint returns the Entrypoint field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceChanges) GetEntrypoint() CommandConfig {
	if o == nil || IsNil(o.Entrypoint.Get()) {
		var ret CommandConfig
		return ret
	}
	return *o.Entrypoint.Get()
}

// GetEntrypointOk returns a tuple with the Entrypoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceChanges) GetEntrypointOk() (*CommandConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entrypoint.Get(), o.Entrypoint.IsSet()
}

// HasEntrypoint returns a boolean if a field has been set.
func (o *ServiceChanges) HasEntrypoint() bool {
	if o != nil && o.Entrypoint.IsSet() {
		return true
	}

	return false
}

// SetEntrypoint gets a reference to the given NullableCommandConfig and assigns it to the Entrypoint field.
func (o *ServiceChanges) SetEntrypoint(v CommandConfig) {
	o.Entrypoint.Set(&v)
}
// SetEntrypointNil sets the value for Entrypoint to be an explicit nil
func (o *ServiceChanges) SetEntrypointNil() {
	o.Entrypoint.Set(nil)
}

// UnsetEntrypoint ensures that no value is present for Entrypoint, not even an explicit nil
func (o *ServiceChanges) UnsetEntrypoint() {
	o.Entrypoint.Unset()
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *ServiceChanges) GetEnvironment() map[string]string {
	if o == nil || IsNil(o.Environment) {
		var ret map[string]string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceChanges) GetEnvironmentOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *ServiceChanges) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given map[string]string and assigns it to the Environment field.
func (o *ServiceChanges) SetEnvironment(v map[string]string) {
	o.Environment = &v
}

// GetHealthcheck returns the Healthcheck field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceChanges) GetHealthcheck() HealthcheckConfig {
	if o == nil || IsNil(o.Healthcheck.Get()) {
		var ret HealthcheckConfig
		return ret
	}
	return *o.Healthcheck.Get()
}

// GetHealthcheckOk returns a tuple with the Healthcheck field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceChanges) GetHealthcheckOk() (*HealthcheckConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Healthcheck.Get(), o.Healthcheck.IsSet()
}

// HasHealthcheck returns a boolean if a field has been set.
func (o *ServiceChanges) HasHealthcheck() bool {
	if o != nil && o.Healthcheck.IsSet() {
		return true
	}

	return false
}

// SetHealthcheck gets a reference to the given NullableHealthcheckConfig and assigns it to the Healthcheck field.
func (o *ServiceChanges) SetHealthcheck(v HealthcheckConfig) {
	o.Healthcheck.Set(&v)
}
// SetHealthcheckNil sets the value for Healthcheck to be an explicit nil
func (o *ServiceChanges) SetHealthcheckNil() {
	o.Healthcheck.Set(nil)
}

// UnsetHealthcheck ensures that no value is present for Healthcheck, not even an explicit nil
func (o *ServiceChanges) UnsetHealthcheck() {
	o.Healthcheck.Unset()
}

// GetImage returns the Image field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceChanges) GetImage() string {
	if o == nil || IsNil(o.Image.Get()) {
		var ret string
		return ret
	}
	return *o.Image.Get()
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceChanges) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Image.Get(), o.Image.IsSet()
}

// HasImage returns a boolean if a field has been set.
func (o *ServiceChanges) HasImage() bool {
	if o != nil && o.Image.IsSet() {
		return true
	}

	return false
}

// SetImage gets a reference to the given NullableString and assigns it to the Image field.
func (o *ServiceChanges) SetImage(v string) {
	o.Image.Set(&v)
}
// SetImageNil sets the value for Image to be an explicit nil
func (o *ServiceChanges) SetImageNil() {
	o.Image.Set(nil)
}

// UnsetImage ensures that no value is present for Image, not even an explicit nil
func (o *ServiceChanges) UnsetImage() {
	o.Image.Unset()
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ServiceChanges) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceChanges) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ServiceChanges) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *ServiceChanges) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetNetworks returns the Networks field value if set, zero value otherwise.
func (o *ServiceChanges) GetNetworks() map[string]ServiceNetworkConfig {
	if o == nil || IsNil(o.Networks) {
		var ret map[string]ServiceNetworkConfig
		return ret
	}
	return o.Networks
}

// GetNetworksOk returns a tuple with the Networks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceChanges) GetNetworksOk() (map[string]ServiceNetworkConfig, bool) {
	if o == nil || IsNil(o.Networks) {
		return map[string]ServiceNetworkConfig{}, false
	}
	return o.Networks, true
}

// HasNetworks returns a boolean if a field has been set.
func (o *ServiceChanges) HasNetworks() bool {
	if o != nil && !IsNil(o.Networks) {
		return true
	}

	return false
}

// SetNetworks gets a reference to the given map[string]ServiceNetworkConfig and assigns it to the Networks field.
func (o *ServiceChanges) SetNetworks(v map[string]ServiceNetworkConfig) {
	o.Networks = v
}

// GetPorts returns the Ports field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceChanges) GetPorts() []PortMapping {
	if o == nil {
		var ret []PortMapping
		return ret
	}
	return o.Ports
}

// GetPortsOk returns a tuple with the Ports field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceChanges) GetPortsOk() ([]PortMapping, bool) {
	if o == nil || IsNil(o.Ports) {
		return nil, false
	}
	return o.Ports, true
}

// HasPorts returns a boolean if a field has been set.
func (o *ServiceChanges) HasPorts() bool {
	if o != nil && !IsNil(o.Ports) {
		return true
	}

	return false
}

// SetPorts gets a reference to the given []PortMapping and assigns it to the Ports field.
func (o *ServiceChanges) SetPorts(v []PortMapping) {
	o.Ports = v
}

// GetRestart returns the Restart field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceChanges) GetRestart() string {
	if o == nil || IsNil(o.Restart.Get()) {
		var ret string
		return ret
	}
	return *o.Restart.Get()
}

// GetRestartOk returns a tuple with the Restart field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceChanges) GetRestartOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Restart.Get(), o.Restart.IsSet()
}

// HasRestart returns a boolean if a field has been set.
func (o *ServiceChanges) HasRestart() bool {
	if o != nil && o.Restart.IsSet() {
		return true
	}

	return false
}

// SetRestart gets a reference to the given NullableString and assigns it to the Restart field.
func (o *ServiceChanges) SetRestart(v string) {
	o.Restart.Set(&v)
}
// SetRestartNil sets the value for Restart to be an explicit nil
func (o *ServiceChanges) SetRestartNil() {
	o.Restart.Set(nil)
}

// UnsetRestart ensures that no value is present for Restart, not even an explicit nil
func (o *ServiceChanges) UnsetRestart() {
	o.Restart.Unset()
}

// GetVolumes returns the Volumes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ServiceChanges) GetVolumes() []VolumeMount2 {
	if o == nil {
		var ret []VolumeMount2
		return ret
	}
	return o.Volumes
}

// GetVolumesOk returns a tuple with the Volumes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ServiceChanges) GetVolumesOk() ([]VolumeMount2, bool) {
	if o == nil || IsNil(o.Volumes) {
		return nil, false
	}
	return o.Volumes, true
}

// HasVolumes returns a boolean if a field has been set.
func (o *ServiceChanges) HasVolumes() bool {
	if o != nil && !IsNil(o.Volumes) {
		return true
	}

	return false
}

// SetVolumes gets a reference to the given []VolumeMount2 and assigns it to the Volumes field.
func (o *ServiceChanges) SetVolumes(v []VolumeMount2) {
	o.Volumes = v
}

func (o ServiceChanges) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceChanges) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Build.IsSet() {
		toSerialize["build"] = o.Build.Get()
	}
	if o.Command.IsSet() {
		toSerialize["command"] = o.Command.Get()
	}
	if !IsNil(o.DependsOn) {
		toSerialize["depends_on"] = o.DependsOn
	}
	if o.Deploy.IsSet() {
		toSerialize["deploy"] = o.Deploy.Get()
	}
	if o.Entrypoint.IsSet() {
		toSerialize["entrypoint"] = o.Entrypoint.Get()
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if o.Healthcheck.IsSet() {
		toSerialize["healthcheck"] = o.Healthcheck.Get()
	}
	if o.Image.IsSet() {
		toSerialize["image"] = o.Image.Get()
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Networks) {
		toSerialize["networks"] = o.Networks
	}
	if o.Ports != nil {
		toSerialize["ports"] = o.Ports
	}
	if o.Restart.IsSet() {
		toSerialize["restart"] = o.Restart.Get()
	}
	if o.Volumes != nil {
		toSerialize["volumes"] = o.Volumes
	}
	return toSerialize, nil
}

type NullableServiceChanges struct {
	value *ServiceChanges
	isSet bool
}

func (v NullableServiceChanges) Get() *ServiceChanges {
	return v.value
}

func (v *NullableServiceChanges) Set(val *ServiceChanges) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceChanges) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceChanges) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceChanges(val *ServiceChanges) *NullableServiceChanges {
	return &NullableServiceChanges{value: val, isSet: true}
}

func (v NullableServiceChanges) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceChanges) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


