/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateCredentialResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateCredentialResponse{}

// UpdateCredentialResponse struct for UpdateCredentialResponse
type UpdateCredentialResponse struct {
	Data GetCredentialData `json:"data"`
	Success bool `json:"success"`
}

type _UpdateCredentialResponse UpdateCredentialResponse

// NewUpdateCredentialResponse instantiates a new UpdateCredentialResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateCredentialResponse(data GetCredentialData, success bool) *UpdateCredentialResponse {
	this := UpdateCredentialResponse{}
	this.Data = data
	this.Success = success
	return &this
}

// NewUpdateCredentialResponseWithDefaults instantiates a new UpdateCredentialResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateCredentialResponseWithDefaults() *UpdateCredentialResponse {
	this := UpdateCredentialResponse{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateCredentialResponse) GetData() GetCredentialData {
	if o == nil {
		var ret GetCredentialData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateCredentialResponse) GetDataOk() (*GetCredentialData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateCredentialResponse) SetData(v GetCredentialData) {
	o.Data = v
}

// GetSuccess returns the Success field value
func (o *UpdateCredentialResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *UpdateCredentialResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *UpdateCredentialResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o UpdateCredentialResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateCredentialResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *UpdateCredentialResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateCredentialResponse := _UpdateCredentialResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateCredentialResponse)

	if err != nil {
		return err
	}

	*o = UpdateCredentialResponse(varUpdateCredentialResponse)

	return err
}

type NullableUpdateCredentialResponse struct {
	value *UpdateCredentialResponse
	isSet bool
}

func (v NullableUpdateCredentialResponse) Get() *UpdateCredentialResponse {
	return v.value
}

func (v *NullableUpdateCredentialResponse) Set(val *UpdateCredentialResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateCredentialResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateCredentialResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateCredentialResponse(val *UpdateCredentialResponse) *NullableUpdateCredentialResponse {
	return &NullableUpdateCredentialResponse{value: val, isSet: true}
}

func (v NullableUpdateCredentialResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateCredentialResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


