/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PermissionsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionsResponse{}

// PermissionsResponse struct for PermissionsResponse
type PermissionsResponse struct {
	Data PermissionsResponseData `json:"data"`
	Success bool `json:"success"`
}

type _PermissionsResponse PermissionsResponse

// NewPermissionsResponse instantiates a new PermissionsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionsResponse(data PermissionsResponseData, success bool) *PermissionsResponse {
	this := PermissionsResponse{}
	this.Data = data
	this.Success = success
	return &this
}

// NewPermissionsResponseWithDefaults instantiates a new PermissionsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionsResponseWithDefaults() *PermissionsResponse {
	this := PermissionsResponse{}
	return &this
}

// GetData returns the Data field value
func (o *PermissionsResponse) GetData() PermissionsResponseData {
	if o == nil {
		var ret PermissionsResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *PermissionsResponse) GetDataOk() (*PermissionsResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *PermissionsResponse) SetData(v PermissionsResponseData) {
	o.Data = v
}

// GetSuccess returns the Success field value
func (o *PermissionsResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *PermissionsResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *PermissionsResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o PermissionsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *PermissionsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPermissionsResponse := _PermissionsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPermissionsResponse)

	if err != nil {
		return err
	}

	*o = PermissionsResponse(varPermissionsResponse)

	return err
}

type NullablePermissionsResponse struct {
	value *PermissionsResponse
	isSet bool
}

func (v NullablePermissionsResponse) Get() *PermissionsResponse {
	return v.value
}

func (v *NullablePermissionsResponse) Set(val *PermissionsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionsResponse(val *PermissionsResponse) *NullablePermissionsResponse {
	return &NullablePermissionsResponse{value: val, isSet: true}
}

func (v NullablePermissionsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


