/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetAPIKeyResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetAPIKeyResponse{}

// GetAPIKeyResponse struct for GetAPIKeyResponse
type GetAPIKeyResponse struct {
	Data APIKeyInfo `json:"data"`
	Success bool `json:"success"`
}

type _GetAPIKeyResponse GetAPIKeyResponse

// NewGetAPIKeyResponse instantiates a new GetAPIKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAPIKeyResponse(data APIKeyInfo, success bool) *GetAPIKeyResponse {
	this := GetAPIKeyResponse{}
	this.Data = data
	this.Success = success
	return &this
}

// NewGetAPIKeyResponseWithDefaults instantiates a new GetAPIKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAPIKeyResponseWithDefaults() *GetAPIKeyResponse {
	this := GetAPIKeyResponse{}
	return &this
}

// GetData returns the Data field value
func (o *GetAPIKeyResponse) GetData() APIKeyInfo {
	if o == nil {
		var ret APIKeyInfo
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *GetAPIKeyResponse) GetDataOk() (*APIKeyInfo, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *GetAPIKeyResponse) SetData(v APIKeyInfo) {
	o.Data = v
}

// GetSuccess returns the Success field value
func (o *GetAPIKeyResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *GetAPIKeyResponse) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *GetAPIKeyResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o GetAPIKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetAPIKeyResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["success"] = o.Success
	return toSerialize, nil
}

func (o *GetAPIKeyResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetAPIKeyResponse := _GetAPIKeyResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetAPIKeyResponse)

	if err != nil {
		return err
	}

	*o = GetAPIKeyResponse(varGetAPIKeyResponse)

	return err
}

type NullableGetAPIKeyResponse struct {
	value *GetAPIKeyResponse
	isSet bool
}

func (v NullableGetAPIKeyResponse) Get() *GetAPIKeyResponse {
	return v.value
}

func (v *NullableGetAPIKeyResponse) Set(val *GetAPIKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAPIKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAPIKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAPIKeyResponse(val *GetAPIKeyResponse) *NullableGetAPIKeyResponse {
	return &NullableGetAPIKeyResponse{value: val, isSet: true}
}

func (v NullableGetAPIKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAPIKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


