/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ContainerStats type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ContainerStats{}

// ContainerStats struct for ContainerStats
type ContainerStats struct {
	BlockReadBytes int32 `json:"block_read_bytes"`
	BlockReadBytesPerSecond NullableFloat32 `json:"block_read_bytes_per_second"`
	BlockReadOps int32 `json:"block_read_ops"`
	BlockWriteBytes int32 `json:"block_write_bytes"`
	BlockWriteBytesPerSecond NullableFloat32 `json:"block_write_bytes_per_second"`
	BlockWriteOps int32 `json:"block_write_ops"`
	CpuPercentOfHost NullableFloat32 `json:"cpu_percent_of_host"`
	CpuPercentOfQuota NullableFloat32 `json:"cpu_percent_of_quota"`
	CpuQuotaCores float32 `json:"cpu_quota_cores"`
	CpuSystemTime int32 `json:"cpu_system_time"`
	CpuThrottledPercent NullableFloat32 `json:"cpu_throttled_percent"`
	CpuUsageCores NullableFloat32 `json:"cpu_usage_cores"`
	CpuUserTime int32 `json:"cpu_user_time"`
	MemoryAnon int32 `json:"memory_anon"`
	MemoryCurrent int32 `json:"memory_current"`
	MemoryFile int32 `json:"memory_file"`
	MemoryInactiveFile int32 `json:"memory_inactive_file"`
	MemoryLimit int32 `json:"memory_limit"`
	MemoryLimitHits int32 `json:"memory_limit_hits"`
	MemoryPeak int32 `json:"memory_peak"`
	MemoryPercentOfHost NullableFloat32 `json:"memory_percent_of_host"`
	MemoryPercentOfLimit NullableFloat32 `json:"memory_percent_of_limit"`
	MemorySwap int32 `json:"memory_swap"`
	MemoryWorkingSet int32 `json:"memory_working_set"`
	Name string `json:"name"`
	NetworkRxBytes int32 `json:"network_rx_bytes"`
	NetworkRxBytesPerSecond NullableFloat32 `json:"network_rx_bytes_per_second"`
	NetworkRxPackets int32 `json:"network_rx_packets"`
	NetworkTxBytes int32 `json:"network_tx_bytes"`
	NetworkTxBytesPerSecond NullableFloat32 `json:"network_tx_bytes_per_second"`
	NetworkTxPackets int32 `json:"network_tx_packets"`
	OomKills int32 `json:"oom_kills"`
	PageFaults int32 `json:"page_faults"`
	PageMajorFaults int32 `json:"page_major_faults"`
	ServiceName string `json:"service_name"`
	State string `json:"state"`
}

type _ContainerStats ContainerStats

// NewContainerStats instantiates a new ContainerStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewContainerStats(blockReadBytes int32, blockReadBytesPerSecond NullableFloat32, blockReadOps int32, blockWriteBytes int32, blockWriteBytesPerSecond NullableFloat32, blockWriteOps int32, cpuPercentOfHost NullableFloat32, cpuPercentOfQuota NullableFloat32, cpuQuotaCores float32, cpuSystemTime int32, cpuThrottledPercent NullableFloat32, cpuUsageCores NullableFloat32, cpuUserTime int32, memoryAnon int32, memoryCurrent int32, memoryFile int32, memoryInactiveFile int32, memoryLimit int32, memoryLimitHits int32, memoryPeak int32, memoryPercentOfHost NullableFloat32, memoryPercentOfLimit NullableFloat32, memorySwap int32, memoryWorkingSet int32, name string, networkRxBytes int32, networkRxBytesPerSecond NullableFloat32, networkRxPackets int32, networkTxBytes int32, networkTxBytesPerSecond NullableFloat32, networkTxPackets int32, oomKills int32, pageFaults int32, pageMajorFaults int32, serviceName string, state string) *ContainerStats {
	this := ContainerStats{}
	this.BlockReadBytes = blockReadBytes
	this.BlockReadBytesPerSecond = blockReadBytesPerSecond
	this.BlockReadOps = blockReadOps
	this.BlockWriteBytes = blockWriteBytes
	this.BlockWriteBytesPerSecond = blockWriteBytesPerSecond
	this.BlockWriteOps = blockWriteOps
	this.CpuPercentOfHost = cpuPercentOfHost
	this.CpuPercentOfQuota = cpuPercentOfQuota
	this.CpuQuotaCores = cpuQuotaCores
	this.CpuSystemTime = cpuSystemTime
	this.CpuThrottledPercent = cpuThrottledPercent
	this.CpuUsageCores = cpuUsageCores
	this.CpuUserTime = cpuUserTime
	this.MemoryAnon = memoryAnon
	this.MemoryCurrent = memoryCurrent
	this.MemoryFile = memoryFile
	this.MemoryInactiveFile = memoryInactiveFile
	this.MemoryLimit = memoryLimit
	this.MemoryLimitHits = memoryLimitHits
	this.MemoryPeak = memoryPeak
	this.MemoryPercentOfHost = memoryPercentOfHost
	this.MemoryPercentOfLimit = memoryPercentOfLimit
	this.MemorySwap = memorySwap
	this.MemoryWorkingSet = memoryWorkingSet
	this.Name = name
	this.NetworkRxBytes = networkRxBytes
	this.NetworkRxBytesPerSecond = networkRxBytesPerSecond
	this.NetworkRxPackets = networkRxPackets
	this.NetworkTxBytes = networkTxBytes
	this.NetworkTxBytesPerSecond = networkTxBytesPerSecond
	this.NetworkTxPackets = networkTxPackets
	this.OomKills = oomKills
	this.PageFaults = pageFaults
	this.PageMajorFaults = pageMajorFaults
	this.ServiceName = serviceName
	this.State = state
	return &this
}

// NewContainerStatsWithDefaults instantiates a new ContainerStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewContainerStatsWithDefaults() *ContainerStats {
	this := ContainerStats{}
	return &this
}

// GetBlockReadBytes returns the BlockReadBytes field value
func (o *ContainerStats) GetBlockReadBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockReadBytes
}

// GetBlockReadBytesOk returns a tuple with the BlockReadBytes field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetBlockReadBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockReadBytes, true
}

// SetBlockReadBytes sets field value
func (o *ContainerStats) SetBlockReadBytes(v int32) {
	o.BlockReadBytes = v
}

// GetBlockReadBytesPerSecond returns the BlockReadBytesPerSecond field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetBlockReadBytesPerSecond() float32 {
	if o == nil || o.BlockReadBytesPerSecond.Get() == nil {
		var ret float32
		return ret
	}

	return *o.BlockReadBytesPerSecond.Get()
}

// GetBlockReadBytesPerSecondOk returns a tuple with the BlockReadBytesPerSecond field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetBlockReadBytesPerSecondOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockReadBytesPerSecond.Get(), o.BlockReadBytesPerSecond.IsSet()
}

// SetBlockReadBytesPerSecond sets field value
func (o *ContainerStats) SetBlockReadBytesPerSecond(v float32) {
	o.BlockReadBytesPerSecond.Set(&v)
}

// GetBlockReadOps returns the BlockReadOps field value
func (o *ContainerStats) GetBlockReadOps() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockReadOps
}

// GetBlockReadOpsOk returns a tuple with the BlockReadOps field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetBlockReadOpsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockReadOps, true
}

// SetBlockReadOps sets field value
func (o *ContainerStats) SetBlockReadOps(v int32) {
	o.BlockReadOps = v
}

// GetBlockWriteBytes returns the BlockWriteBytes field value
func (o *ContainerStats) GetBlockWriteBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockWriteBytes
}

// GetBlockWriteBytesOk returns a tuple with the BlockWriteBytes field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetBlockWriteBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockWriteBytes, true
}

// SetBlockWriteBytes sets field value
func (o *ContainerStats) SetBlockWriteBytes(v int32) {
	o.BlockWriteBytes = v
}

// GetBlockWriteBytesPerSecond returns the BlockWriteBytesPerSecond field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetBlockWriteBytesPerSecond() float32 {
	if o == nil || o.BlockWriteBytesPerSecond.Get() == nil {
		var ret float32
		return ret
	}

	return *o.BlockWriteBytesPerSecond.Get()
}

// GetBlockWriteBytesPerSecondOk returns a tuple with the BlockWriteBytesPerSecond field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetBlockWriteBytesPerSecondOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BlockWriteBytesPerSecond.Get(), o.BlockWriteBytesPerSecond.IsSet()
}

// SetBlockWriteBytesPerSecond sets field value
func (o *ContainerStats) SetBlockWriteBytesPerSecond(v float32) {
	o.BlockWriteBytesPerSecond.Set(&v)
}

// GetBlockWriteOps returns the BlockWriteOps field value
func (o *ContainerStats) GetBlockWriteOps() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.BlockWriteOps
}

// GetBlockWriteOpsOk returns a tuple with the BlockWriteOps field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetBlockWriteOpsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BlockWriteOps, true
}

// SetBlockWriteOps sets field value
func (o *ContainerStats) SetBlockWriteOps(v int32) {
	o.BlockWriteOps = v
}

// GetCpuPercentOfHost returns the CpuPercentOfHost field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetCpuPercentOfHost() float32 {
	if o == nil || o.CpuPercentOfHost.Get() == nil {
		var ret float32
		return ret
	}

	return *o.CpuPercentOfHost.Get()
}

// GetCpuPercentOfHostOk returns a tuple with the CpuPercentOfHost field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetCpuPercentOfHostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CpuPercentOfHost.Get(), o.CpuPercentOfHost.IsSet()
}

// SetCpuPercentOfHost sets field value
func (o *ContainerStats) SetCpuPercentOfHost(v float32) {
	o.CpuPercentOfHost.Set(&v)
}

// GetCpuPercentOfQuota returns the CpuPercentOfQuota field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetCpuPercentOfQuota() float32 {
	if o == nil || o.CpuPercentOfQuota.Get() == nil {
		var ret float32
		return ret
	}

	return *o.CpuPercentOfQuota.Get()
}

// GetCpuPercentOfQuotaOk returns a tuple with the CpuPercentOfQuota field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetCpuPercentOfQuotaOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CpuPercentOfQuota.Get(), o.CpuPercentOfQuota.IsSet()
}

// SetCpuPercentOfQuota sets field value
func (o *ContainerStats) SetCpuPercentOfQuota(v float32) {
	o.CpuPercentOfQuota.Set(&v)
}

// GetCpuQuotaCores returns the CpuQuotaCores field value
func (o *ContainerStats) GetCpuQuotaCores() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CpuQuotaCores
}

// GetCpuQuotaCoresOk returns a tuple with the CpuQuotaCores field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetCpuQuotaCoresOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuQuotaCores, true
}

// SetCpuQuotaCores sets field value
func (o *ContainerStats) SetCpuQuotaCores(v float32) {
	o.CpuQuotaCores = v
}

// GetCpuSystemTime returns the CpuSystemTime field value
func (o *ContainerStats) GetCpuSystemTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CpuSystemTime
}

// GetCpuSystemTimeOk returns a tuple with the CpuSystemTime field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetCpuSystemTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuSystemTime, true
}

// SetCpuSystemTime sets field value
func (o *ContainerStats) SetCpuSystemTime(v int32) {
	o.CpuSystemTime = v
}

// GetCpuThrottledPercent returns the CpuThrottledPercent field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetCpuThrottledPercent() float32 {
	if o == nil || o.CpuThrottledPercent.Get() == nil {
		var ret float32
		return ret
	}

	return *o.CpuThrottledPercent.Get()
}

// GetCpuThrottledPercentOk returns a tuple with the CpuThrottledPercent field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetCpuThrottledPercentOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CpuThrottledPercent.Get(), o.CpuThrottledPercent.IsSet()
}

// SetCpuThrottledPercent sets field value
func (o *ContainerStats) SetCpuThrottledPercent(v float32) {
	o.CpuThrottledPercent.Set(&v)
}

// GetCpuUsageCores returns the CpuUsageCores field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetCpuUsageCores() float32 {
	if o == nil || o.CpuUsageCores.Get() == nil {
		var ret float32
		return ret
	}

	return *o.CpuUsageCores.Get()
}

// GetCpuUsageCoresOk returns a tuple with the CpuUsageCores field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetCpuUsageCoresOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.CpuUsageCores.Get(), o.CpuUsageCores.IsSet()
}

// SetCpuUsageCores sets field value
func (o *ContainerStats) SetCpuUsageCores(v float32) {
	o.CpuUsageCores.Set(&v)
}

// GetCpuUserTime returns the CpuUserTime field value
func (o *ContainerStats) GetCpuUserTime() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CpuUserTime
}

// GetCpuUserTimeOk returns a tuple with the CpuUserTime field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetCpuUserTimeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CpuUserTime, true
}

// SetCpuUserTime sets field value
func (o *ContainerStats) SetCpuUserTime(v int32) {
	o.CpuUserTime = v
}

// GetMemoryAnon returns the MemoryAnon field value
func (o *ContainerStats) GetMemoryAnon() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryAnon
}

// GetMemoryAnonOk returns a tuple with the MemoryAnon field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetMemoryAnonOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryAnon, true
}

// SetMemoryAnon sets field value
func (o *ContainerStats) SetMemoryAnon(v int32) {
	o.MemoryAnon = v
}

// GetMemoryCurrent returns the MemoryCurrent field value
func (o *ContainerStats) GetMemoryCurrent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryCurrent
}

// GetMemoryCurrentOk returns a tuple with the MemoryCurrent field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetMemoryCurrentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryCurrent, true
}

// SetMemoryCurrent sets field value
func (o *ContainerStats) SetMemoryCurrent(v int32) {
	o.MemoryCurrent = v
}

// GetMemoryFile returns the MemoryFile field value
func (o *ContainerStats) GetMemoryFile() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryFile
}

// GetMemoryFileOk returns a tuple with the MemoryFile field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetMemoryFileOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryFile, true
}

// SetMemoryFile sets field value
func (o *ContainerStats) SetMemoryFile(v int32) {
	o.MemoryFile = v
}

// GetMemoryInactiveFile returns the MemoryInactiveFile field value
func (o *ContainerStats) GetMemoryInactiveFile() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryInactiveFile
}

// GetMemoryInactiveFileOk returns a tuple with the MemoryInactiveFile field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetMemoryInactiveFileOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryInactiveFile, true
}

// SetMemoryInactiveFile sets field value
func (o *ContainerStats) SetMemoryInactiveFile(v int32) {
	o.MemoryInactiveFile = v
}

// GetMemoryLimit returns the MemoryLimit field value
func (o *ContainerStats) GetMemoryLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryLimit
}

// GetMemoryLimitOk returns a tuple with the MemoryLimit field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetMemoryLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryLimit, true
}

// SetMemoryLimit sets field value
func (o *ContainerStats) SetMemoryLimit(v int32) {
	o.MemoryLimit = v
}

// GetMemoryLimitHits returns the MemoryLimitHits field value
func (o *ContainerStats) GetMemoryLimitHits() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryLimitHits
}

// GetMemoryLimitHitsOk returns a tuple with the MemoryLimitHits field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetMemoryLimitHitsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryLimitHits, true
}

// SetMemoryLimitHits sets field value
func (o *ContainerStats) SetMemoryLimitHits(v int32) {
	o.MemoryLimitHits = v
}

// GetMemoryPeak returns the MemoryPeak field value
func (o *ContainerStats) GetMemoryPeak() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryPeak
}

// GetMemoryPeakOk returns a tuple with the MemoryPeak field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetMemoryPeakOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryPeak, true
}

// SetMemoryPeak sets field value
func (o *ContainerStats) SetMemoryPeak(v int32) {
	o.MemoryPeak = v
}

// GetMemoryPercentOfHost returns the MemoryPercentOfHost field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetMemoryPercentOfHost() float32 {
	if o == nil || o.MemoryPercentOfHost.Get() == nil {
		var ret float32
		return ret
	}

	return *o.MemoryPercentOfHost.Get()
}

// GetMemoryPercentOfHostOk returns a tuple with the MemoryPercentOfHost field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetMemoryPercentOfHostOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MemoryPercentOfHost.Get(), o.MemoryPercentOfHost.IsSet()
}

// SetMemoryPercentOfHost sets field value
func (o *ContainerStats) SetMemoryPercentOfHost(v float32) {
	o.MemoryPercentOfHost.Set(&v)
}

// GetMemoryPercentOfLimit returns the MemoryPercentOfLimit field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetMemoryPercentOfLimit() float32 {
	if o == nil || o.MemoryPercentOfLimit.Get() == nil {
		var ret float32
		return ret
	}

	return *o.MemoryPercentOfLimit.Get()
}

// GetMemoryPercentOfLimitOk returns a tuple with the MemoryPercentOfLimit field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetMemoryPercentOfLimitOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MemoryPercentOfLimit.Get(), o.MemoryPercentOfLimit.IsSet()
}

// SetMemoryPercentOfLimit sets field value
func (o *ContainerStats) SetMemoryPercentOfLimit(v float32) {
	o.MemoryPercentOfLimit.Set(&v)
}

// GetMemorySwap returns the MemorySwap field value
func (o *ContainerStats) GetMemorySwap() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemorySwap
}

// GetMemorySwapOk returns a tuple with the MemorySwap field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetMemorySwapOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemorySwap, true
}

// SetMemorySwap sets field value
func (o *ContainerStats) SetMemorySwap(v int32) {
	o.MemorySwap = v
}

// GetMemoryWorkingSet returns the MemoryWorkingSet field value
func (o *ContainerStats) GetMemoryWorkingSet() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryWorkingSet
}

// GetMemoryWorkingSetOk returns a tuple with the MemoryWorkingSet field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetMemoryWorkingSetOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MemoryWorkingSet, true
}

// SetMemoryWorkingSet sets field value
func (o *ContainerStats) SetMemoryWorkingSet(v int32) {
	o.MemoryWorkingSet = v
}

// GetName returns the Name field value
func (o *ContainerStats) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ContainerStats) SetName(v string) {
	o.Name = v
}

// GetNetworkRxBytes returns the NetworkRxBytes field value
func (o *ContainerStats) GetNetworkRxBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetworkRxBytes
}

// GetNetworkRxBytesOk returns a tuple with the NetworkRxBytes field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetNetworkRxBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkRxBytes, true
}

// SetNetworkRxBytes sets field value
func (o *ContainerStats) SetNetworkRxBytes(v int32) {
	o.NetworkRxBytes = v
}

// GetNetworkRxBytesPerSecond returns the NetworkRxBytesPerSecond field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetNetworkRxBytesPerSecond() float32 {
	if o == nil || o.NetworkRxBytesPerSecond.Get() == nil {
		var ret float32
		return ret
	}

	return *o.NetworkRxBytesPerSecond.Get()
}

// GetNetworkRxBytesPerSecondOk returns a tuple with the NetworkRxBytesPerSecond field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetNetworkRxBytesPerSecondOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkRxBytesPerSecond.Get(), o.NetworkRxBytesPerSecond.IsSet()
}

// SetNetworkRxBytesPerSecond sets field value
func (o *ContainerStats) SetNetworkRxBytesPerSecond(v float32) {
	o.NetworkRxBytesPerSecond.Set(&v)
}

// GetNetworkRxPackets returns the NetworkRxPackets field value
func (o *ContainerStats) GetNetworkRxPackets() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetworkRxPackets
}

// GetNetworkRxPacketsOk returns a tuple with the NetworkRxPackets field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetNetworkRxPacketsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkRxPackets, true
}

// SetNetworkRxPackets sets field value
func (o *ContainerStats) SetNetworkRxPackets(v int32) {
	o.NetworkRxPackets = v
}

// GetNetworkTxBytes returns the NetworkTxBytes field value
func (o *ContainerStats) GetNetworkTxBytes() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetworkTxBytes
}

// GetNetworkTxBytesOk returns a tuple with the NetworkTxBytes field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetNetworkTxBytesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkTxBytes, true
}

// SetNetworkTxBytes sets field value
func (o *ContainerStats) SetNetworkTxBytes(v int32) {
	o.NetworkTxBytes = v
}

// GetNetworkTxBytesPerSecond returns the NetworkTxBytesPerSecond field value
// If the value is explicit nil, the zero value for float32 will be returned
func (o *ContainerStats) GetNetworkTxBytesPerSecond() float32 {
	if o == nil || o.NetworkTxBytesPerSecond.Get() == nil {
		var ret float32
		return ret
	}

	return *o.NetworkTxBytesPerSecond.Get()
}

// GetNetworkTxBytesPerSecondOk returns a tuple with the NetworkTxBytesPerSecond field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ContainerStats) GetNetworkTxBytesPerSecondOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return o.NetworkTxBytesPerSecond.Get(), o.NetworkTxBytesPerSecond.IsSet()
}

// SetNetworkTxBytesPerSecond sets field value
func (o *ContainerStats) SetNetworkTxBytesPerSecond(v float32) {
	o.NetworkTxBytesPerSecond.Set(&v)
}

// GetNetworkTxPackets returns the NetworkTxPackets field value
func (o *ContainerStats) GetNetworkTxPackets() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.NetworkTxPackets
}

// GetNetworkTxPacketsOk returns a tuple with the NetworkTxPackets field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetNetworkTxPacketsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NetworkTxPackets, true
}

// SetNetworkTxPackets sets field value
func (o *ContainerStats) SetNetworkTxPackets(v int32) {
	o.NetworkTxPackets = v
}

// GetOomKills returns the OomKills field value
func (o *ContainerStats) GetOomKills() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.OomKills
}

// GetOomKillsOk returns a tuple with the OomKills field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetOomKillsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OomKills, true
}

// SetOomKills sets field value
func (o *ContainerStats) SetOomKills(v int32) {
	o.OomKills = v
}

// GetPageFaults returns the PageFaults field value
func (o *ContainerStats) GetPageFaults() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageFaults
}

// GetPageFaultsOk returns a tuple with the PageFaults field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetPageFaultsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageFaults, true
}

// SetPageFaults sets field value
func (o *ContainerStats) SetPageFaults(v int32) {
	o.PageFaults = v
}

// GetPageMajorFaults returns the PageMajorFaults field value
func (o *ContainerStats) GetPageMajorFaults() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.PageMajorFaults
}

// GetPageMajorFaultsOk returns a tuple with the PageMajorFaults field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetPageMajorFaultsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageMajorFaults, true
}

// SetPageMajorFaults sets field value
func (o *ContainerStats) SetPageMajorFaults(v int32) {
	o.PageMajorFaults = v
}

// GetServiceName returns the ServiceName field value
func (o *ContainerStats) GetServiceName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceName
}

// GetServiceNameOk returns a tuple with the ServiceName field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetServiceNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceName, true
}

// SetServiceName sets field value
func (o *ContainerStats) SetServiceName(v string) {
	o.ServiceName = v
}

// GetState returns the State field value
func (o *ContainerStats) GetState() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.State
}

// GetStateOk returns a tuple with the State field value
// and a boolean to check if the value has been set.
func (o *ContainerStats) GetStateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.State, true
}

// SetState sets field value
func (o *ContainerStats) SetState(v string) {
	o.State = v
}

func (o ContainerStats) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ContainerStats) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["block_read_bytes"] = o.BlockReadBytes
	toSerialize["block_read_bytes_per_second"] = o.BlockReadBytesPerSecond.Get()
	toSerialize["block_read_ops"] = o.BlockReadOps
	toSerialize["block_write_bytes"] = o.BlockWriteBytes
	toSerialize["block_write_bytes_per_second"] = o.BlockWriteBytesPerSecond.Get()
	toSerialize["block_write_ops"] = o.BlockWriteOps
	toSerialize["cpu_percent_of_host"] = o.CpuPercentOfHost.Get()
	toSerialize["cpu_percent_of_quota"] = o.CpuPercentOfQuota.Get()
	toSerialize["cpu_quota_cores"] = o.CpuQuotaCores
	toSerialize["cpu_system_time"] = o.CpuSystemTime
	toSerialize["cpu_throttled_percent"] = o.CpuThrottledPercent.Get()
	toSerialize["cpu_usage_cores"] = o.CpuUsageCores.Get()
	toSerialize["cpu_user_time"] = o.CpuUserTime
	toSerialize["memory_anon"] = o.MemoryAnon
	toSerialize["memory_current"] = o.MemoryCurrent
	toSerialize["memory_file"] = o.MemoryFile
	toSerialize["memory_inactive_file"] = o.MemoryInactiveFile
	toSerialize["memory_limit"] = o.MemoryLimit
	toSerialize["memory_limit_hits"] = o.MemoryLimitHits
	toSerialize["memory_peak"] = o.MemoryPeak
	toSerialize["memory_percent_of_host"] = o.MemoryPercentOfHost.Get()
	toSerialize["memory_percent_of_limit"] = o.MemoryPercentOfLimit.Get()
	toSerialize["memory_swap"] = o.MemorySwap
	toSerialize["memory_working_set"] = o.MemoryWorkingSet
	toSerialize["name"] = o.Name
	toSerialize["network_rx_bytes"] = o.NetworkRxBytes
	toSerialize["network_rx_bytes_per_second"] = o.NetworkRxBytesPerSecond.Get()
	toSerialize["network_rx_packets"] = o.NetworkRxPackets
	toSerialize["network_tx_bytes"] = o.NetworkTxBytes
	toSerialize["network_tx_bytes_per_second"] = o.NetworkTxBytesPerSecond.Get()
	toSerialize["network_tx_packets"] = o.NetworkTxPackets
	toSerialize["oom_kills"] = o.OomKills
	toSerialize["page_faults"] = o.PageFaults
	toSerialize["page_major_faults"] = o.PageMajorFaults
	toSerialize["service_name"] = o.ServiceName
	toSerialize["state"] = o.State
	return toSerialize, nil
}

func (o *ContainerStats) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"block_read_bytes",
		"block_read_bytes_per_second",
		"block_read_ops",
		"block_write_bytes",
		"block_write_bytes_per_second",
		"block_write_ops",
		"cpu_percent_of_host",
		"cpu_percent_of_quota",
		"cpu_quota_cores",
		"cpu_system_time",
		"cpu_throttled_percent",
		"cpu_usage_cores",
		"cpu_user_time",
		"memory_anon",
		"memory_current",
		"memory_file",
		"memory_inactive_file",
		"memory_limit",
		"memory_limit_hits",
		"memory_peak",
		"memory_percent_of_host",
		"memory_percent_of_limit",
		"memory_swap",
		"memory_working_set",
		"name",
		"network_rx_bytes",
		"network_rx_bytes_per_second",
		"network_rx_packets",
		"network_tx_bytes",
		"network_tx_bytes_per_second",
		"network_tx_packets",
		"oom_kills",
		"page_faults",
		"page_major_faults",
		"service_name",
		"state",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varContainerStats := _ContainerStats{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varContainerStats)

	if err != nil {
		return err
	}

	*o = ContainerStats(varContainerStats)

	return err
}

type NullableContainerStats struct {
	value *ContainerStats
	isSet bool
}

func (v NullableContainerStats) Get() *ContainerStats {
	return v.value
}

func (v *NullableContainerStats) Set(val *ContainerStats) {
	v.value = val
	v.isSet = true
}

func (v NullableContainerStats) IsSet() bool {
	return v.isSet
}

func (v *NullableContainerStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableContainerStats(val *ContainerStats) *NullableContainerStats {
	return &NullableContainerStats{value: val, isSet: true}
}

func (v NullableContainerStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableContainerStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


