/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListServersData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListServersData{}

// ListServersData struct for ListServersData
type ListServersData struct {
	Servers []ServerInfo `json:"servers"`
}

type _ListServersData ListServersData

// NewListServersData instantiates a new ListServersData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListServersData(servers []ServerInfo) *ListServersData {
	this := ListServersData{}
	this.Servers = servers
	return &this
}

// NewListServersDataWithDefaults instantiates a new ListServersData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListServersDataWithDefaults() *ListServersData {
	this := ListServersData{}
	return &this
}

// GetServers returns the Servers field value
func (o *ListServersData) GetServers() []ServerInfo {
	if o == nil {
		var ret []ServerInfo
		return ret
	}

	return o.Servers
}

// GetServersOk returns a tuple with the Servers field value
// and a boolean to check if the value has been set.
func (o *ListServersData) GetServersOk() ([]ServerInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.Servers, true
}

// SetServers sets field value
func (o *ListServersData) SetServers(v []ServerInfo) {
	o.Servers = v
}

func (o ListServersData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListServersData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["servers"] = o.Servers
	return toSerialize, nil
}

func (o *ListServersData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"servers",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListServersData := _ListServersData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListServersData)

	if err != nil {
		return err
	}

	*o = ListServersData(varListServersData)

	return err
}

type NullableListServersData struct {
	value *ListServersData
	isSet bool
}

func (v NullableListServersData) Get() *ListServersData {
	return v.value
}

func (v *NullableListServersData) Set(val *ListServersData) {
	v.value = val
	v.isSet = true
}

func (v NullableListServersData) IsSet() bool {
	return v.isSet
}

func (v *NullableListServersData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListServersData(val *ListServersData) *NullableListServersData {
	return &NullableListServersData{value: val, isSet: true}
}

func (v NullableListServersData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListServersData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


