/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the StackStatusEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StackStatusEvent{}

// StackStatusEvent struct for StackStatusEvent
type StackStatusEvent struct {
	Running int32 `json:"running"`
	ServerId int32 `json:"server_id"`
	Services int32 `json:"services"`
	StackName string `json:"stack_name"`
	Status string `json:"status"`
	Stopped int32 `json:"stopped"`
	Timestamp string `json:"timestamp"`
	Type string `json:"type"`
}

type _StackStatusEvent StackStatusEvent

// NewStackStatusEvent instantiates a new StackStatusEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStackStatusEvent(running int32, serverId int32, services int32, stackName string, status string, stopped int32, timestamp string, type_ string) *StackStatusEvent {
	this := StackStatusEvent{}
	this.Running = running
	this.ServerId = serverId
	this.Services = services
	this.StackName = stackName
	this.Status = status
	this.Stopped = stopped
	this.Timestamp = timestamp
	this.Type = type_
	return &this
}

// NewStackStatusEventWithDefaults instantiates a new StackStatusEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStackStatusEventWithDefaults() *StackStatusEvent {
	this := StackStatusEvent{}
	return &this
}

// GetRunning returns the Running field value
func (o *StackStatusEvent) GetRunning() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Running
}

// GetRunningOk returns a tuple with the Running field value
// and a boolean to check if the value has been set.
func (o *StackStatusEvent) GetRunningOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Running, true
}

// SetRunning sets field value
func (o *StackStatusEvent) SetRunning(v int32) {
	o.Running = v
}

// GetServerId returns the ServerId field value
func (o *StackStatusEvent) GetServerId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ServerId
}

// GetServerIdOk returns a tuple with the ServerId field value
// and a boolean to check if the value has been set.
func (o *StackStatusEvent) GetServerIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServerId, true
}

// SetServerId sets field value
func (o *StackStatusEvent) SetServerId(v int32) {
	o.ServerId = v
}

// GetServices returns the Services field value
func (o *StackStatusEvent) GetServices() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Services
}

// GetServicesOk returns a tuple with the Services field value
// and a boolean to check if the value has been set.
func (o *StackStatusEvent) GetServicesOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Services, true
}

// SetServices sets field value
func (o *StackStatusEvent) SetServices(v int32) {
	o.Services = v
}

// GetStackName returns the StackName field value
func (o *StackStatusEvent) GetStackName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StackName
}

// GetStackNameOk returns a tuple with the StackName field value
// and a boolean to check if the value has been set.
func (o *StackStatusEvent) GetStackNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StackName, true
}

// SetStackName sets field value
func (o *StackStatusEvent) SetStackName(v string) {
	o.StackName = v
}

// GetStatus returns the Status field value
func (o *StackStatusEvent) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *StackStatusEvent) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *StackStatusEvent) SetStatus(v string) {
	o.Status = v
}

// GetStopped returns the Stopped field value
func (o *StackStatusEvent) GetStopped() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Stopped
}

// GetStoppedOk returns a tuple with the Stopped field value
// and a boolean to check if the value has been set.
func (o *StackStatusEvent) GetStoppedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stopped, true
}

// SetStopped sets field value
func (o *StackStatusEvent) SetStopped(v int32) {
	o.Stopped = v
}

// GetTimestamp returns the Timestamp field value
func (o *StackStatusEvent) GetTimestamp() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value
// and a boolean to check if the value has been set.
func (o *StackStatusEvent) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Timestamp, true
}

// SetTimestamp sets field value
func (o *StackStatusEvent) SetTimestamp(v string) {
	o.Timestamp = v
}

// GetType returns the Type field value
func (o *StackStatusEvent) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *StackStatusEvent) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *StackStatusEvent) SetType(v string) {
	o.Type = v
}

func (o StackStatusEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StackStatusEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["running"] = o.Running
	toSerialize["server_id"] = o.ServerId
	toSerialize["services"] = o.Services
	toSerialize["stack_name"] = o.StackName
	toSerialize["status"] = o.Status
	toSerialize["stopped"] = o.Stopped
	toSerialize["timestamp"] = o.Timestamp
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *StackStatusEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"running",
		"server_id",
		"services",
		"stack_name",
		"status",
		"stopped",
		"timestamp",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varStackStatusEvent := _StackStatusEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varStackStatusEvent)

	if err != nil {
		return err
	}

	*o = StackStatusEvent(varStackStatusEvent)

	return err
}

type NullableStackStatusEvent struct {
	value *StackStatusEvent
	isSet bool
}

func (v NullableStackStatusEvent) Get() *StackStatusEvent {
	return v.value
}

func (v *NullableStackStatusEvent) Set(val *StackStatusEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableStackStatusEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableStackStatusEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStackStatusEvent(val *StackStatusEvent) *NullableStackStatusEvent {
	return &NullableStackStatusEvent{value: val, isSet: true}
}

func (v NullableStackStatusEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStackStatusEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


