/*
Berth API

Berth: Opinionated docker compose stack management API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package berth

import (
	"encoding/json"
)

// checks if the RestartPolicyConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestartPolicyConfig{}

// RestartPolicyConfig struct for RestartPolicyConfig
type RestartPolicyConfig struct {
	Condition *string `json:"condition,omitempty"`
	Delay *string `json:"delay,omitempty"`
	MaxAttempts NullableInt32 `json:"max_attempts,omitempty"`
	Window *string `json:"window,omitempty"`
}

// NewRestartPolicyConfig instantiates a new RestartPolicyConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestartPolicyConfig() *RestartPolicyConfig {
	this := RestartPolicyConfig{}
	return &this
}

// NewRestartPolicyConfigWithDefaults instantiates a new RestartPolicyConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestartPolicyConfigWithDefaults() *RestartPolicyConfig {
	this := RestartPolicyConfig{}
	return &this
}

// GetCondition returns the Condition field value if set, zero value otherwise.
func (o *RestartPolicyConfig) GetCondition() string {
	if o == nil || IsNil(o.Condition) {
		var ret string
		return ret
	}
	return *o.Condition
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestartPolicyConfig) GetConditionOk() (*string, bool) {
	if o == nil || IsNil(o.Condition) {
		return nil, false
	}
	return o.Condition, true
}

// HasCondition returns a boolean if a field has been set.
func (o *RestartPolicyConfig) HasCondition() bool {
	if o != nil && !IsNil(o.Condition) {
		return true
	}

	return false
}

// SetCondition gets a reference to the given string and assigns it to the Condition field.
func (o *RestartPolicyConfig) SetCondition(v string) {
	o.Condition = &v
}

// GetDelay returns the Delay field value if set, zero value otherwise.
func (o *RestartPolicyConfig) GetDelay() string {
	if o == nil || IsNil(o.Delay) {
		var ret string
		return ret
	}
	return *o.Delay
}

// GetDelayOk returns a tuple with the Delay field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestartPolicyConfig) GetDelayOk() (*string, bool) {
	if o == nil || IsNil(o.Delay) {
		return nil, false
	}
	return o.Delay, true
}

// HasDelay returns a boolean if a field has been set.
func (o *RestartPolicyConfig) HasDelay() bool {
	if o != nil && !IsNil(o.Delay) {
		return true
	}

	return false
}

// SetDelay gets a reference to the given string and assigns it to the Delay field.
func (o *RestartPolicyConfig) SetDelay(v string) {
	o.Delay = &v
}

// GetMaxAttempts returns the MaxAttempts field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RestartPolicyConfig) GetMaxAttempts() int32 {
	if o == nil || IsNil(o.MaxAttempts.Get()) {
		var ret int32
		return ret
	}
	return *o.MaxAttempts.Get()
}

// GetMaxAttemptsOk returns a tuple with the MaxAttempts field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RestartPolicyConfig) GetMaxAttemptsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.MaxAttempts.Get(), o.MaxAttempts.IsSet()
}

// HasMaxAttempts returns a boolean if a field has been set.
func (o *RestartPolicyConfig) HasMaxAttempts() bool {
	if o != nil && o.MaxAttempts.IsSet() {
		return true
	}

	return false
}

// SetMaxAttempts gets a reference to the given NullableInt32 and assigns it to the MaxAttempts field.
func (o *RestartPolicyConfig) SetMaxAttempts(v int32) {
	o.MaxAttempts.Set(&v)
}
// SetMaxAttemptsNil sets the value for MaxAttempts to be an explicit nil
func (o *RestartPolicyConfig) SetMaxAttemptsNil() {
	o.MaxAttempts.Set(nil)
}

// UnsetMaxAttempts ensures that no value is present for MaxAttempts, not even an explicit nil
func (o *RestartPolicyConfig) UnsetMaxAttempts() {
	o.MaxAttempts.Unset()
}

// GetWindow returns the Window field value if set, zero value otherwise.
func (o *RestartPolicyConfig) GetWindow() string {
	if o == nil || IsNil(o.Window) {
		var ret string
		return ret
	}
	return *o.Window
}

// GetWindowOk returns a tuple with the Window field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestartPolicyConfig) GetWindowOk() (*string, bool) {
	if o == nil || IsNil(o.Window) {
		return nil, false
	}
	return o.Window, true
}

// HasWindow returns a boolean if a field has been set.
func (o *RestartPolicyConfig) HasWindow() bool {
	if o != nil && !IsNil(o.Window) {
		return true
	}

	return false
}

// SetWindow gets a reference to the given string and assigns it to the Window field.
func (o *RestartPolicyConfig) SetWindow(v string) {
	o.Window = &v
}

func (o RestartPolicyConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestartPolicyConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Condition) {
		toSerialize["condition"] = o.Condition
	}
	if !IsNil(o.Delay) {
		toSerialize["delay"] = o.Delay
	}
	if o.MaxAttempts.IsSet() {
		toSerialize["max_attempts"] = o.MaxAttempts.Get()
	}
	if !IsNil(o.Window) {
		toSerialize["window"] = o.Window
	}
	return toSerialize, nil
}

type NullableRestartPolicyConfig struct {
	value *RestartPolicyConfig
	isSet bool
}

func (v NullableRestartPolicyConfig) Get() *RestartPolicyConfig {
	return v.value
}

func (v *NullableRestartPolicyConfig) Set(val *RestartPolicyConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableRestartPolicyConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableRestartPolicyConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestartPolicyConfig(val *RestartPolicyConfig) *NullableRestartPolicyConfig {
	return &NullableRestartPolicyConfig{value: val, isSet: true}
}

func (v NullableRestartPolicyConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestartPolicyConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


